### ISSUE TITLE
Multi-draft repos

### ISSUE THREAD

**Issue by hildjj** [martinthomson/i-d-template#10]
I would like to have multiple draft-*.md files in my repo.

**Comment by martinthomson** [comment]
Acknowledged and yes.

The HTTP working group has files that support this.  If you thought that the makefile was arcane before, just you wait.

**Comment by hildjj** [comment]
I like arcane.  Please add comments.

**Comment by martinthomson** [comment]
Addressed in https://github.com/martinthomson/i-d-template/commit/25824612b3de764a83d72f

There are no doubt cosmetic improvements to be added.
