### ISSUE TITLE
Branch links

### ISSUE THREAD

**Issue by chrysn** [martinthomson/i-d-template#100]
The gh-pages branch contains builds for every branch, but the "Editor's copy" and "Compare Working group..." links always show the master version, even if the user is browsing them from a branch.

I'd like to see the builds of the branches linked too, but changing README.md for every branch is not an option to me.

The solution I'd propose is to make the build process generate a `/+branches/index.html` file, which contains "branch copy", "compare WG draft to branch" and "compare master to branch" links for each branch.

With that design, it'd be even an option that `/+branches/` be instructed to inspect the referrer for a branch guess, so we could have links like "Editor's copy (→ github.io/.../), Editor branch (→ github.io/draft-name/+branches/#go-to-branch)" that javascript-redirect to github.io/draft-name/<branch-from-referrer>/  or the #go-to-diff that redirect to an appropriate rfcdiff address, but that could be a second step.

Would you consider adding that, and/or would you accept a PR if I find time to do it myself?

**Comment by chrysn** [comment]
I just noticed that "compare master to branch" would usually not make sense as it would contain the reverse delta of all changes to master since that was created. Unless we're ready to (additionally) render a common-ancestor-with-master directory for each branch, that link should not be included per branch, while "compare to WG draft" still makes sense (assuming that branches rebase or merge on occasion sounds reasonable, and a draft release would be such an occasion).

**Comment by martinthomson** [comment]
You are the second person to ask about improving diff.  It would be reasonable to generate a diff with master for a branch, but I don't currently require that rfcdiff is installed in CI.  That's a pretty big barrier.  It might have to be an optional feature.  Since you only need a URI to use the online rfcdiff, maybe concentrate on how you might decorate a generated draft with the right link automatically.

**Comment by chrysn** [comment]
On Tue, May 09, 2017 at 07:25:16PM -0700, Martin Thomson wrote:
> [...] but I don't currently require that rfcdiff is installed in CI.

I was only thinking about online rfcdiff, not about generating deltas in
CI. I'd just like to have it linked in a way that it can be used without
the reader knowing at which URI to find the rendered branches.

I've sketched up a quick basic version that adds the features that will
probably be sufficient. (Building additional versions for each branch
from the common ancestor with master would have been too messy in the
Makefiles for a first sketch).
