### ISSUE TITLE
Note branch versions in gh-pages

### ISSUE THREAD

**Issue by chrysn** [martinthomson/i-d-template#101]
The commit messages in gh-pages mention only a single commit hash (presumably of master), but take input from all branches.

I'd suggest that a line be added for each built branch and their respective commit hashes, for otherwise that information can only be obtained by checking which changes have been incorporated or by making assumptions about which branches were pushed to the commit server at build-time.

(From my PoV, please consider this low priority; it'd be a nice addition but most of the time the assumption that everything is in the latest state holds anyway.)

**Comment by martinthomson** [comment]
The commit message should show the commit hash for the commit that generated the specific change.  Changes that originate on branches should include a hash for a commit on that branch.  Changes on master will identify a commit on master.  I just checked the QUIC repo and everything seems right there:

* https://github.com/quicwg/base-drafts/commit/a5141f2d701 on gh-pages was triggered by https://github.com/quicwg/base-drafts/commit/68f7f04 on the invert_connection_id branch; it only contains changes in /invert_connection_id/*
* https://github.com/quicwg/base-drafts/commit/a7258157b was triggered by https://github.com/quicwg/base-drafts/commit/03f08f6 which was on master; it contains trivial changes to the HTML in the root directory
