### ISSUE TITLE
Optimization for CI: use `kdrfc -r`

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#106]
(Please read this after the I-D deadline.)

After having waited waiting for the umpteenth recompilation of Python lxml:  

Maybe use `kdrfc -r` to build from markdown (kramdown flavor), which uses the tools server instance of xml2rfc instead of a locally installed one.

Pro:

* Doesn't need an xml2rfc installation, which needs about 5 CPU seconds and dominates the wait for CI builds[^1].
* For local processing, make sure the most recent version of xml2rfc is actually being used.

[^1]:  (followed by the refcache fills; I need to figure out a way to parallelize those)

Con:

* Relies on another point of failure (tools server).
* Error messages are slightly budgered by the tools server, but still clearly visible.
* Warning messages from xml2rfc are invisible unless they are accompanied by an error.

**Comment by martinthomson** [comment]
I tried running this locally and was surprised that it doesn't manage a pipeline nicely.  As in you can't do `kdrfc -r <x.md >x.txt`, nor can it produce HTML. I'll open issues.

**Comment by martinthomson** [comment]
I have a new optimization for C-I that should be superior than this.  It still requires occasional downloading of entries in the refcache, but it doesn't require installation of software.

The QUIC draft builds went from over 2 minutes to a shade over 30 seconds.

The new circle CI configuration uses a docker image that has software pre-installed.  It also caches the template and the refcache.  The refcache caching only benefits builds done in close proximity, but is a considerable improvement for those builds.
