### ISSUE TITLE
"No file named draft-*.xml" with -00 draft filename

### ISSUE THREAD

**Issue by strugee** [martinthomson/i-d-template#107]
I've just set up a repository using this template. When I named my draft `draft-jordan-foobar-00.xml`, `make -f lib/setup.mk` threw an error about it not being able to find the file, but when I renamed it to `draft-jordan-foobar-latest.xml` everything worked. Seems like this is mostly a documentation problem?

**Comment by martinthomson** [comment]
The trick here is to omit the name from the title.  The "-latest" is just something you put in the body of drafts in place of the version number.  You don't need or want a version number in the name of the file, as you submit new versions, keeping the same name is easier.

**Comment by strugee** [comment]
Ah, okay. Thanks for clarifying; I'm new to spec writing :)
