### ISSUE TITLE
Trailing whitespace check breaks files

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#110]
While I hate trailing whitespace as much as the next guy, preventing checkin when people use an editor that generates it is pretty harsh.  (The easy solution is to switch to DOS line ends, in which case the check doesn't work any more :-).

The wholesale removal of whitespace from existing files that this triggers is going to cloud the history.

(Oh, and the use of trailing whitespace as a format effector actually is a markdown feature.  Bleh, I know.)

**Comment by MikeBishop** [comment]
We should fix that CRLF breaks the whitespace check.  ;-)

**Comment by martinthomson** [comment]
Hmm, the cost here is minor (it's a simple fix) for the individual adding the whitespace.  So simple that it can be automated, which I've helped with.  `make fix-lint` does just that.

The cost for new contributors is higher, so I believe that the check is worthwhile.  The editor problem has [a solution](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#trim_trailing_whitespace).
