### ISSUE TITLE
Case-sensitive draft upload checks

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#111]
```
mbishop@michbish-dsktop:~/github/quic$ make upload
curl -sS -D .draft-ietf-quic-http-08.upload -F "user=Michael.Bishop@microsoft.com" -F "xml=@draft-ietf-quic-http-08.xml" \
        "https://datatracker.ietf.org/api/submit" && echo && \
  (grep -q ' 200 OK' .draft-ietf-quic-http-08.upload >/dev/null 2>&1 || (cat .draft-ietf-quic-http-08.upload 1>&2 && ! rm -f .draft-ietf-quic-http-08.upload))
Validation Error: [u'Submitter michael.bishop@microsoft.com is not one of the document authors']
```

E-mail addresses are not case-sensitive, so this check shouldn't be either.

Worse, it was easier to change the `user.email` value than the document, so I did that -- and it failed the same way.  Apparently `user.email` gets lower-cased before it's stored.

**Comment by MikeBishop** [comment]
Note that I'm uncertain whether this is Datatracker or the template -- looks like it might be Datatracker.

**Comment by martinthomson** [comment]
yeah, it's the datatracker

**Comment by martinthomson** [comment]
Fixed in the tracker.
