### ISSUE TITLE
printf() spew

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#112]
> mbishop@SEA-WPWIN:~/github/http-misc-extensions$ make update
> Makefile:1: lib/main.mk: No such file or directory
> git clone -q --depth 10 -b master https://github.com/martinthomson/i-d-template.git lib
> lib/main.mk:96: .targets.mk: No such file or directory
> lib/build-targets.sh: line 13: printf: -%: invalid option
> printf: usage: printf [-v var] format [arguments]
> [ ...previous two lines repeat many times...]
> git -C lib pull
> Already up-to-date.

Assuming this is another platform difference, and it appears that I'm picking up a printf built into bash rather than the printf binary.

**Comment by martinthomson** [comment]
This is probably because `git tag --list <draftname>-[0-9][0-9]` returns an empty list.  Why `[ "${#tags[@]}" -gt 0 ]` is true in that case would be a mystery.

Platform compatibility is really annoying sometimes.

**Comment by MikeBishop** [comment]
Potential solution to mystery:  Multiple drafts in the repo, not all of which have been submitted.  Tags for the repo would be non-empty, but tags for any particular draft could be.

**Comment by MikeBishop** [comment]
...no, it looks like you're filtering out the list to the specific draft.  I don't know.  I'm seeing this on https://github.com/MikeBishop/http-misc-extensions, if you want to clone it and check for a repro in your environment.
