### ISSUE TITLE
Renaming drafts doesn't rebuild .targets.mk

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#115]
If you rename a draft, but haven't yet committed the new instance, build-targets.sh doesn't generate submit targets for the new name because it's looking at HEAD rather than the working directory.  If you discover this and commit the rename, it still doesn't work because .targets.mk doesn't get rebuilt.

The workaround is to manually delete .targets.mk after committing a rename.

**Comment by martinthomson** [comment]
Actually, build-targets.mk looks at the set of tags on the repo, so it probably won't work even then.

I didn't want to re-run that target on every change, so there's a trade-off.  Running `make clean` occasionally isn't that awful, is it?

**Comment by MikeBishop** [comment]
It does work, it just builds a -00 of the new name because there's no tag, which is the correct behavior.  (Of course, you have to manually provide the old name when updating to Datatracker, but that seems like expecting too much of the template.)  Running `make clean` is equivalent to manually deleting, which isn't onerous in itself.  The issue is that it's not obvious you need to do that to make it work.

Ideally, there would be a way to tell make that the target needs to be rebuilt if the set of files changes without making it triggered every time an existing file changes, but at a cursory glance I don't see an easy way to do that.

**Comment by MikeBishop** [comment]
Thinking "out loud":  Maybe make invokes the recipe on every change, but the recipe itself short-circuits unless either the set of files or tags has changed.  But that would require some state persistence from when .targets.mk was last run.

**Comment by martinthomson** [comment]
OK, this one should be fixed now.  I've opted to refactor things a little so that we have the set of tags on hand (that means fewer calls to git tag happily).
