### ISSUE TITLE
make submit not working

### ISSUE THREAD

**Issue by hildjj** [martinthomson/i-d-template#12]
I think after you fixed #10, you need to try `make submit`.  I get:

    make: *** No rule to make target `draft-ietf-unicorn-protocol-00.txt', needed by `submit'.  Stop.

I also tried tagging.

**Comment by martinthomson** [comment]
What version of make are you running?  I tested with 4.0 and 3.82 and they both worked.

**Comment by hildjj** [comment]
OSX 10.10.4 default is gmake 3.81.  I can update with homebrew and re-try I guess.

**Comment by hildjj** [comment]
Seems to work with gmake 4.1.  Homebrew magic: `brew install homebrew/dupes/make`, then use `gmake` instead of `make`, or rename/symlink.  Suggest an addition to the docs.

**Comment by martinthomson** [comment]
Added that to the build system, you now get a nice warning.
