### ISSUE TITLE
Issues branch

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#121]
It'd be nice if issues were published onto gh-pages, rather than into a separate branch; that would make them available from the Web, and would make it simpler for third parties to get all of the WG's state in one go.

**Comment by martinthomson** [comment]
Should be fixed now.

**Comment by mnot** [comment]
I see the .js and .json, but issues.html doesn't seem to have come across -- how do we instantiate that?

**Comment by martinthomson** [comment]
Hmm, I noted that.  It looks like the target was failing all the time (I suppress errors for that step because it fails so often).  Should be OK now.
