### ISSUE TITLE
Empty rfc2629.xslt

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#123]
If you try to build an XSLT-based repo on a machine that doesn't have xsltproc installed, it fails with an appropriate error.  All well and good -- install xsltproc and try again.

This time it fails because lib/rfc2629.xslt is empty.  You can recover by deleting that file, but to a normal user it's not apparent that it's safe to do so.  (Delete part of the template???)  If production of the file fails, make should delete it so it starts from a clean slate next time.

**Comment by martinthomson** [comment]
Ahh, that's a simple fix.  I didn't realize that .DELETE_ON_ERROR wasn't the default.
