### ISSUE TITLE
How to show the issues in issues.html?

### ISSUE THREAD

**Issue by fpalombini** [martinthomson/i-d-template#133]
Right now you set up a link to issues.html in the gh-pages, but I couldn't find anything on how to use the template to show the issues there (or what are the "saved issues"). That's for an existing directory, I guess for new directories that is done automatically during the set up? Anyway,it would be nice with some doc whenever you have time :) Thanks!

**Comment by martinthomson** [comment]
Thanks for asking.  The html should load the issues automatically, but I had a bug where the issues weren't being updated properly.  Typing /help in the input box on the html page should give you the help you need.  (This isn't a proper substitute for the GitHub interface, but I do want to ensure that the issues are at least searchable offline.)

If you don't have an `issues.html` file on `gh-pages`, that's a(nother) bug.
