### ISSUE TITLE
CSS feedback redux

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#135]
... from Anitra:

- [x] There's too much variation in typefaces. There should really only be one thing changing at a time; font, font size, colour, weight, etc.

- [x] e.g., at the header, there's large-black h1, light-grey-medium-size draft-name, black-medium-size h2 and body text. This is especially evident on iOS, where the first three elements are all different sizes.

- [x] line length is good on desktop, but too many words per line on iOS.

- [x] margins are too big on iOS. 

- [x] author names at bottom of draft are over-bolded.

**Comment by mnot** [comment]
See #149.

**Comment by mnot** [comment]
margins on mobile and line length now #147

**Comment by martinthomson** [comment]
@mnot, check out #150.
