### ISSUE TITLE
Smaller ToC?

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#140]
One of the things I did in my XSLT was make the both the size and leading of the ToC smaller, to help avoid wrapping / scrolling for more documents. 

WDYT? Happy to give a PR.

**Comment by mnot** [comment]
E.g., see: http://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html

**Comment by martinthomson** [comment]
Yes, the ToC tends to be too narrow, so smaller text is fine.  As long as you also observe the guidance from Anitra about the multitude of styles.

**Comment by martinthomson** [comment]
You might also consider shaving down the indent for the nested lists.  That's part of the problem.

**Comment by mnot** [comment]
Thoughts?

![screen shot 2018-04-04 at 11 52 21 am](https://user-images.githubusercontent.com/74384/38284458-ad9a2090-37fe-11e8-87e8-c9edb53f0b1d.png)

**Comment by martinthomson** [comment]
I think that we could have slightly bigger font, and cut down the spacing to compensate (line spacing and indentation).

**Comment by mnot** [comment]
If we make it bigger, it's going to be too-similar-but-still-different from the body text; when you make changes in size, they need to look intentional. (I played around with this a fair amount).

**Comment by mnot** [comment]
LGTM, thx.
