### ISSUE TITLE
addstyle.sed deletes all XSLT-generated content

### ISSUE THREAD

**Issue by jyasskin** [martinthomson/i-d-template#141]
I just created a new repository with `USE_XSLT=true` and 4fee301bee8dfdf60d560b7a684aa0dd09c3f54c checked out into `lib`, and running `make` yields an HTML file with only style and no content. The intermediate `.htmltmp` file has all of the content on a single line after the `</style>`, and `addstyle.sed` appears to remove that line.

**Comment by martinthomson** [comment]
I haven't seen that particular failure mode.  `addstyle.sed` ensures that it copies out the remainder of the line after `</style>`, but I suppose that could fail if there are two style blocks.

I assume that you have a recent xsltproc and that the checkout for https://github.com/reschke/xml2rfc is recent.  That produces elements on separate lines throughout for me, so I don't see this particular issue.

**Comment by martinthomson** [comment]
Recent changes to the workflow mean that this isn't as likely to happen.  This still happens, but it's off the happy path (you have to author XML now).
