### ISSUE TITLE
Pre-commit hook lints unstaged documents

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#143]
1. Modify a draft (in a valid way) and stage it
2. Modify a draft in a way that will fail linting
3. Attempt to commit the valid change to the draft

The linter runs on all drafts *including* the staged version, but should only run on the drafts being committed.

**Comment by MikeBishop** [comment]
This may require separate changes to the built-in lint command and the QUIC repo's python one, but I think the fix is the same -- the Makefile should populate a variable with the drafts actually being built, and then the lint:: rules should operate on that variable rather than `$(drafts)` or `draft-*.md`.

**Comment by MikeBishop** [comment]
Possibly related, the pre-commit hook says this:

```
files=($(git status --porcelain draft-* | sed '/^[MARCU]/{s/.*draft-/draft-/;p;};d' | sort))
tmpfiles=()
trap 'rm -f "${tmpfiles[@]}" "${txtfiles[@]}"' EXIT
for f in "${files[@]}"; do
    tmp="${f%.*}"-tmp$$."${f##*.}"
    tmpfiles+=("$tmp")
    tmpfiles+=("${tmp%.*}.txt")
    # This makes a copy of the staged file.
    (git show :"$f" 2>/dev/null || cat "$f") > "$tmp"
done
[ "${#files[@]}" -eq 0 ] && exit 0

tmpfiles+=("$targets_file")
"$MAKE" txt lint "drafts=${files[*]%.*}" DISABLE_TARGETS_UPDATE=true
```

So the tmpfiles collection is assembled, but not actually built.  I think tmpfiles needs to be what's passed to the Make command, but when I do that ghpages complains that the html/txt output is listed more than once in the same rule.

**Comment by martinthomson** [comment]
@MikeBishop I think that this is fixed.  Can you confirm?

**Comment by martinthomson** [comment]
Is this the quic-specific linting?  Because that just checks every markdown file in the repo.  If you want to fix that, that's easy enough.
