### ISSUE TITLE
Margins on mobile

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#147]
On my iPhone, the side margins are considerable, making the text very small. 

This is not reproducible in Safari's "responsive mode", which is annoying.

**Comment by mnot** [comment]
Also, line lengths are too long. But margins need to be reduced first.

**Comment by martinthomson** [comment]
I'm getting the big margins on my phone as well, and am having the same issues with the responsive design mode in Firefox.

**Comment by mnot** [comment]
See #151
