### ISSUE TITLE
CSS for index

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#155]
isn't present (as per @reschke)

**Comment by martinthomson** [comment]
There was some styling, it was just...poor.

Try https://quicwg.github.io/base-drafts/ now.  PRs for refinement welcome, of course.

**Comment by mnot** [comment]
Pretty, but Julian meant this index: https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#rfc.index

**Comment by mnot** [comment]
(sorry for the ambiguity; er, two issues for the price of one?)

**Comment by martinthomson** [comment]
I've made a few changes and while I'm not happy with indexes, most of that is a problem with xml2rfc.  I've opened a few issues there.
