### ISSUE TITLE
Tag-based upload not working (or confusing error) with TravisCI

### ISSUE THREAD

**Issue by jyasskin** [martinthomson/i-d-template#158]
I tried to upload using the instructions in https://github.com/martinthomson/i-d-template/blob/master/doc/SUBMITTING.md#automated-process twice recently (https://travis-ci.org/WICG/webpackage/builds/392069709 and https://travis-ci.org/WICG/webpackage/builds/392467197), and got the following error:

```
xml2rfc -q draft-yasskin-wpack-bundled-exchanges.xml -o draft-yasskin-wpack-bundled-exchanges.htmltmp --html
sed -f lib/addstyle.sed draft-yasskin-wpack-bundled-exchanges.htmltmp > draft-yasskin-wpack-bundled-exchanges.html
make: *** No rule to make target `draft-yasskin-http-origin-signed-responses-04.xml', needed by `latest'.  Stop.
rm draft-yasskin-wpack-bundled-exchanges.htmltmp draft-yasskin-httpbis-origin-signed-exchanges-impl.htmltmp draft-yasskin-dispatch-web-packaging.htmltmp draft-yasskin-webpackage-use-cases.htmltmp draft-yasskin-http-origin-signed-responses.htmltmp
```

Locally, both `make draft-yasskin-http-origin-signed-responses-04.xml` and `make upload` work.

This isn't urgent since the local process works.

**Comment by martinthomson** [comment]
Oh, I think that there must have been a regression.  The version of make on travis is strange and I don't use travis, so it tends to break.  There's a hack somewhere that fixed this, but I can't remember how that works.  Thanks for reporting.

**Comment by kmindi** [comment]
this still seems to not work (https://travis-ci.com/github/secureCryptoConfig/secureCryptoConfig/builds/181423588#L318). Yet for my tag build it already has an error creating .targets.mk

**Comment by larseggert** [comment]
Is there any benefit of retaining CircleCI over GitHub actions? Can we just rip out CircleCI entirely?

**Comment by MikeBishop** [comment]
Mostly for existing repos.  There's no need to break something that works and require them to transition.  However, if Circle ever requires a manual step to keep it working, switching to GitHub Actions seems just as easy.

**Comment by martinthomson** [comment]
I'm going to close this without a fix.  Travis builds might still work, but I'm no longer testing them.
