### ISSUE TITLE
Preservation of pull requests

### ISSUE THREAD

**Issue by chrysn** [martinthomson/i-d-template#159]
The `ghissues` target does a good job in preserving issues and pull to be independent of github. What is not preserved though is the content of rejected pull requests, or their original content in case they taken in with a strategy like cherry-pick. It appears that github keeps the commits mentioned in the PRs around, but encourages the (in my impression common and sane) workflow of deleting the remote branch once the PR is closed in any fashion. (Local users may or may not keep that branch around, but that's hard to reach for the purpose of documenting our process.)

I think it's worth considering whether and how those can or should be preserved. (And if the conclusion is that it's too much of a hassle (or "yeah we should but nobody has time to do it"), document that as part of the workflow).

One simple-but-ugly method that comes to my mind is having an "earlier-considerations" branch that has an empty (or README-only) tree, and ghissues checks whether any PR references a commit that's not mentioned in any branch and takes that into the parent-commits list of the next (tree-wise identical) commit on earlier-considerations.

**Comment by martinthomson** [comment]
The best way to manage this would be to create branches that pull in the referenced PR changes.  Putting those on the repo would ensure that the commits are available.  e.g.,

```
git fetch <remote> <branch>:pr/<number>
```

We can probably add something to the CI build so that this happens automatically.

**Comment by martinthomson** [comment]
After looking into this, we can't push those branches back to the repo if the PR was from a fork, and those are the ones that you want to save (branches on the main repo are naturally fine).  The reason we can't do that is that it would allow PRs from forks to get access to the token used to push to the repo.

**Comment by martinthomson** [comment]
Included in recent archive changes.
