### ISSUE TITLE
Changing document name?

### ISSUE THREAD

**Issue by josephlhall** [martinthomson/i-d-template#164]
When a WG adopts a document the draft goes from something like `draft-hall-foo-bar` to `draft-ietf-foo-bar`. In the framework of this Markdown template, how does that work? In my case, I now have a repo with a different title than the document and I started tagging them over again at -00. However, I have to do a `make draft-ietf-foo-bar-00.xml` before `make submit` will work otherwise I get an error like `gmake: *** No rule to make target 'draft-ietf-foo-bar-01.xml', needed by 'draft-ietf-foo-bar-01.txt'.  Stop.`

Just wondering if there is a flow for changing document names and keeping the same repo that folks here would recommend.

**Comment by martinthomson** [comment]
Rename the draft (`git mv draft-hall-... draft-ietf-...`) and start tagging from -00.  As long as you run `make submit` before tagging, that should produce the *next* (i.e., untagged) draft.

That said, the logic here is complex and `make clean` is a nice reset option.
