### ISSUE TITLE
Uploading to datatracker with secondary emails

### ISSUE THREAD

**Issue by larseggert** [martinthomson/i-d-template#172]
My datatracker login has a different primary email than the one I put into I-Ds (and which is also my git `user.email`). That email, however, is configured as an alternate active email address in my datatracker profile.

`make upload` still fails with:
```
No such user: lars@XYZ.com
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Date: Tue, 20 Nov 2018 06:55:49 GMT
Server: Apache
Vary: Origin,Accept-Encoding
X-Frame-Options: SAMEORIGIN
ETag: "8bd40123a4ada4d9797448088c5a3fbc"
Strict-Transport-Security: max-age=31536000
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline' data: https://datatracker.ietf.org/ https://www.ietf.org/;
Connection: close
Transfer-Encoding: chunked
Content-Type: text/plain
```

Is this supposed to work? Or do I need to change my datatracker login email, or the email I put into the draft?

**Comment by martinthomson** [comment]
I've raised this with Henrik several times and his response was: 

> >  On 2018-04-26 14:26, Martin Thomson wrote:
> > Why does the submission form care about a mismatch between login and
>> primary email?  Why not accept any validated email address?
>
> You're concerned only with making things easy here, which is fine.  I'm
>also concerned with the potential for mischief.  For that reason, I wanted
>API submissions to be bound to a login, and coded things that way.
>
> Of course things can be changed to make the code derive the login from
> any active email address.  It will increase the potential for mischief,
> but I don't know how much.
>
> But in any case, the reason why the submission API cares at the moment
> is that it was coded to recognize logins, not derive the logins from
> any of the active email addresses registered for a login.

and

> On 2018-04-26 16:12, Martin Thomson wrote:
>> I suspect that the occurrence of use of emails for drafts that differ
>> from a primary login is high enough that you want to use active emails
>> and not logins.  Think about me+wgname@domain.com for wgname drafts,
>> for example.
>
> On the other hand, this is the first instance we've seen of this.

I don't find that particularly satisfactory, but there you go.  There's more to that thread, but this is the best response I could extract.

I've opened https://trac.tools.ietf.org/tools/ietfdb/ticket/2639

**Comment by larseggert** [comment]
Thanks. I'm with you in that I don't see how this makes any difference to the attack surface.

**Comment by britram** [comment]
+1 to "this doesn't matter from a security standpoint" but I think we've already had that conversation

**Comment by martinthomson** [comment]
Thanks to Robert, we're rolling with this.  Expect progress.
