### ISSUE TITLE
CircleCI errors unless `xml2rfc` is manually updated

### ISSUE THREAD

**Issue by linuxwolf** [martinthomson/i-d-template#175]
CircleCI is failing in [this project](https://circleci.com/gh/cose-wg/cose-rfc8152bis/9?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) due to some errors from `xml2rfc`:

```
...
xml2rfc -q draft-schaad-cose-rfc8152bis-algs.xml -o draft-schaad-cose-rfc8152bis-algs.txt --text
Error: utf_8_encode() argument 1 must be str, not bytes
Error: Unable to parse the XML document: draft-schaad-cose-rfc8152bis-algs.xml
 draft-schaad-cose-rfc8152bis-algs.xml: Line 1158: Unable to resolve external request: "reference.RFC.2104"
lib/main.mk:83: recipe for target 'draft-schaad-cose-rfc8152bis-algs.txt' failed
...
```

Using the latest Docker image locally it works once `xml2rfc` is updated to the latest.

**Comment by martinthomson** [comment]
I've added something to the template that reports configuration of the core tools that change often.  This error should have been transient, but now at least you can match things up.
