### ISSUE TITLE
NBSP weirdness

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#179]
If you look at

https://tools.ietf.org/rfcdiff?url1=https://tools.ietf.org/id/draft-ietf-cbor-7049bis.txt&url2=https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.txt

right now, you can see that the manual build that generated yesterday's I-D and the automatic build from the CI differ in how they handle the NBSP that is inserted between "Section" and the automatically generated section numbers (the NBSPs turn into plain spaces in the CI build).  This is confusing when trying to find out what the current diffs are.  More intriguingly, I don't even know where to start finding the origin of that difference.

**Comment by martinthomson** [comment]
That's annoying for sure.  I wonder if the problem here is in different xml2rfc versions.  Are you using the latest version?  If so, I can nudge the docker image build so that the CI builds update as well.

**Comment by martinthomson** [comment]
I see now that there are many more differences.  In table formatting and other things.  This is clearly an xml2rfc problem, so I'm going to attribute it to that.  I could maybe try to synchronize with datatracker better, I guess.
