### ISSUE TITLE
"Editor's copy" links to README.md

### ISSUE THREAD

**Issue by chucklever** [martinthomson/i-d-template#183]
https://github.com/chucklever/i-d-rpc-tls/tree/master

Clicking on "Editor's Copy" takes me back to the README instead of linking to the current draft. I've set up CircleCI and also tried pushing the gh-pages branch manually.

**Comment by martinthomson** [comment]
For some reason your repository is configured to pull from `master` for its website, rather than `gh-pages`.  You can fix this in [settings](https://github.com/chucklever/i-d-rpc-tls/settings).  The content on `gh-pages` looks fine.
