### ISSUE TITLE
Update README.md when adding another draft

### ISSUE THREAD

**Issue by rmarx** [martinthomson/i-d-template#184]
Hello Martin,

Thanks for this project, it has helped me tremendously setting up my first I-D. 

It did take me some time figuring out how to add a second draft to the same repo (after having setup everything for 1 draft only) and having it show up. 
Apparently the setup correctly generates the gh-pages and all the rest, but does not update the README.md to include the links to the editor's draft etc. for the new I-D. This made it look for a while that the whole process didn't work correctly. 

The workaround was to just manually edit the README (https://github.com/quiclog/internet-drafts/commit/496421225553f032465bee4a1bc983a93c2cb3f0), which is obviously not a lot of work, but as a first time user, it was still unexpected that the README wasn't updated.

Possible solutions:
- Mention this behaviour in the docs (possibly also mentioning that just running 'make' again is enough for it to pick up the new document)
- Update the README automatically when a new draft is discovered (though this might be trickier if people have manually edited the README...)

**Comment by martinthomson** [comment]
Yeah, I should probably document this bit.  You can regenerate the README, but it's not obvious how to do so.

```
git rm README.md
git commit -m "Remove README" README.md
make -f lib/setup.mk README.md
```

I'll see if I can find a place to put this info.
