### ISSUE TITLE
make upload did not generate XML file

### ISSUE THREAD

**Issue by alvestrand** [martinthomson/i-d-template#185]
I have a repo where I'm writing a draft in Markdown (https://github.com/alvestrand/simulcast-ssrc)
I tried to do "make upload", and got a response saying that it was unable to make -00.txt because there was no -00.xml file.

I was able to get around this issue by:
- Adding the tag with git tag -a
- Doing "make draftname-00.xml" explicitly
- Uploading by hand

Either the instructions are incomplete, or I'm reading them wrong.

Note: I have no CI of any kind (either Circle CI or Travis) on this repo.

**Comment by martinthomson** [comment]
`make upload` doesn't upload anything unless the current HEAD is tagged.  And if nothing it tagged, it won't be able to build `draft-...-00.xml` because it doesn't know what `draft-...-00` is.  But that is the only condition on that process.  Did you tag before attempting this?

**Comment by alvestrand** [comment]
I didn't tag before trying this, because the instructions didn't say you had to tag - they seemed to imply that "make upload" would auto-tag. That may be a problem with the instructions, or with my reading of them.

**Comment by martinthomson** [comment]
The change in 3852c50 should address some of this concern.
