### ISSUE TITLE
What's the problem with Xcode's make?

### ISSUE THREAD

**Issue by irons** [martinthomson/i-d-template#19]
I filed [this PR](https://github.com/ietf-wg-acme/acme/pull/35) on ietf-wg-acme to fix an XCode/Xcode typo, and they asked me to file it upstream. Upstream, in f746176, the typo now appears in an advisory to install Homebrew's version of make, and an assertion about Xcode's version being "subtly broken".

What sort of subtle brokenness is at issue? Is there an openradar for the problem? Thanks.

**Comment by martinthomson** [comment]
X[cC]ode is somehow incapable of handling something related to the $(eval ) functions used to synthesize targets.  I've never really investigated the problem any more than that.  Installing the Homebrew version of make is a very good workaround.
