### ISSUE TITLE
Make an actual template

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/i-d-template#191]
See https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

**Comment by maifeeulasad** [comment]
This would be really cool, plus if someone makes some video tutorial about how to use this repository

**Comment by MikeBishop** [comment]
It seems like it should be really simple -- I took at stab at https://github.com/MikeBishop/idt-template/, and derived repos can be generated by hitting https://github.com/MikeBishop/idt-template/generate.  Happy to transfer ownership to @martinthomson if you'd like.

**Comment by MikeBishop** [comment]
The more complex piece is that some of the files get populated with the draft name during the "normal" setup.  It would be nice to be able to refresh those files after a draft rename, and I believe a tool for that already exists; we might just want to have an easy shortcut to make sure all of that happens.

It would also be nice to rebuild this template repo whenever the files that get populated are modified (e.g. the Makefile, the CI files, etc.).  That requires more work, I think.

**Comment by maifeeulasad** [comment]
Damn @MikeBishop , your repo is on fire. That is quite is to use. Thanks. Thanks, a lot.

**Comment by martinthomson** [comment]
[This](https://github.com/martinthomson/i-d-template/issues/191#issuecomment-768489163) is why I've always shied away from doing this.  I want a good solution for managing draft renames before getting into that.  However, that might be as simple as adding a target along the lines of:

```make
.PHONY: update-readme
update-readme:
        $(MAKE) -f $(LIBDIR)/setup.mk README.md
```

As I think that `README.md` is the only file that really needs to be tweaked.

**Comment by martinthomson** [comment]
A [template exists](https://github.com/martinthomson/internet-draft-template).  Read [the instructions](https://github.com/martinthomson/i-d-template/blob/main/doc/TEMPLATE.md) if you need help.  Very little manual intervention involved.  I'll open a ticket to add a workflow for updating the README (which is sometimes needed).
