### ISSUE TITLE
I dislike the "condensed" font for titles.

### ISSUE THREAD

**Issue by jyasskin** [martinthomson/i-d-template#204]
https://github.com/martinthomson/i-d-template/blob/master/v3.css selects the "Cabin Condensed" font for section titles. I find the narrow letters hard to read and would prefer a normal width font instead.

**Comment by martinthomson** [comment]
Hmm, I really like condensed fonts for headings.

Aside from a personal preference for condensed fonts, long headings are very common in drafts and RFCs and a narrower rendering helps keep things on one line.

Try tweaking the heading font in [HTTP/3](https://quicwg.org/base-drafts/draft-ietf-quic-http.html) to use [Lato](https://www.latofonts.com/).  That's a font that I almost selected (you can get semi-bold from the site, note that Google fonts don't have that variant).  That pushes the title onto two lines.  You can reduce font size to allow for more space; changes cascade from there.

The previous version used Roboto Condensed, which I decided against this time as it was both more narrow and used shapes that I found to be inconsistent with the body text.

Ideally there would be something fairly neutral, but only slightly wider on the whole.  I couldn't find that font.  If you have a suggestion, please offer one.

**Comment by martinthomson** [comment]
I know that this is unlikely to be better, but I'm considering https://fonts.google.com/specimen/Sofia+Sans+Semi+Condensed/about as an alternative.  Still condensed, but only by half.

**Comment by martinthomson** [comment]
Done. Now we get to see whether this elicits any reaction.
