### ISSUE TITLE
Docker failed to build

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#210]
The Docker image didn't get updated with `python3-dateutil`.  The GitHub hooks for the most recent commits in your repo say the Docker image failed to build, but the listing on Docker Hub says all builds were successful -- those just aren't listed.

I don't think I can debug this any further, but the archive script is failing because its dependencies aren't in the image.

**Comment by martinthomson** [comment]
Fixed by adding a noninteractive option to the build.
