### ISSUE TITLE
Can't seem to build with list

### ISSUE THREAD

**Issue by nrooney** [martinthomson/i-d-template#22]
Hey! I am getting errors on the build due to using <list style="symbols">. See below:

`ERROR: Unable to validate the XML document: draft-rooney-marnew-report-latest.xml
 draft-rooney-marnew-report-latest.xml: Line 38: Element section content does not follow the DTD, expecting ((t | figure | texttable | iref)* , section*), got (t section section t list t)`

I guess I ambeing a n00b again, but any help would be great!

If it hekps I followed your syntax from https://github.com/webpush-wg/webpush-protocol/blob/master/draft-ietf-webpush-protocol.xml

**Comment by martinthomson** [comment]
Don't use XML, it's always going to do this to you.  Markdown is your friend.

Take a look at line 38.  Somewhere around there you have a `<list>` that isn't inside a `<t>`.

(Email is probably a better channel for these sorts of questions.)
