### ISSUE TITLE
kramdown-rfc should be called with the --v3 flag if v3 processing is desired

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#224]
The current template uses --v2v3 to generate RFCXMLv3 but doesn't tell kramdown-rfc that v3 features will be available.

(There is also a weird nbsp problem that I'm still trying to understand.)

**Comment by martinthomson** [comment]
@cabo, thanks for poking.  Is the support for v3 robust enough in kramdown-rfc that we can avoid the conversion?  Or is this still advisable?

**Comment by cabo** [comment]
There is almost no v3 support in kramdown-rfc; it relies on the v2v3 conversion provided by xml2rfc.
Apart from lack of time, a good argument for that is that v3 isn't really that stable yet, so it is better to have xml2rfc generate the v3 that it then itself processes than try for kramdown-rfc to hit a moving target.
But there are features in kramdown-rfc already (such as the contributors section, svg support, etc.) that require v3 support in xml2rfc; kramdown-rfc needs to be told that this is available to make use of it.

**Comment by martinthomson** [comment]
Great.  That makes sense.

I've got the flag in now, so we'll see how that works out.

Thanks again.
