### ISSUE TITLE
Removed labels

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/i-d-template#229]
The archival process doesn't update issues in some narrow circumstances, which leads to some skew.  For instance, when I deleted a label in the QUIC repository, the affected issues weren't updated in the archive.

This might be a case for re-running the archive process from scratch, but I don't know the complete set of changes that might result in this being necessary.  For the moment, I'm comfortable with that being manual, as this particular problem seems like it is manageable.  I've added a few defensive measures for this specific problem, and will fix the QUIC archive manually.

Filing this issue to track this in case more cases like this crop up.

**Comment by MikeBishop** [comment]
More generally, the archive process follow's GitHub's definition of "modified."  If GitHub doesn't consider an issue modified, it won't be redownloaded.  Another non-modification change, I suspect, would be if someone renames their GitHub user account.  A fresh download would find the new username, but it doesn't cause every issue they've ever touched to become modified.

**Comment by martinthomson** [comment]
Closed in favour of #329 (fortuitous numbering being purely accidental).
