### ISSUE TITLE
Investigate empty responses

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/i-d-template#231]
https://github.com/martinthomson/quic-bit-grease/runs/820487138?check_suite_focus=true shows an error.  Find out what is going on.  That repo has (or had) no issues open at the time, so it is possible that this is just a corner case in the script.  It also might be a problem with credentials or something more serious.

**Comment by Bren2010** [comment]
We seem to have the same issue with the MLS WG: https://github.com/mlswg/mls-protocol/runs/861824665?check_suite_focus=true

**Comment by martinthomson** [comment]
This turned out to be a credentials issue.  The token that GitHub Actions provides needs to be used in combination with the `$GITHUB_ACTOR` value when used as a username portion for pushes.  That is `git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}`.  However, including `$GITHUB_ACTOR` in the authorization token in the same way caused the errors as shown.
