### ISSUE TITLE
Remove `--no-site-packages` flag from virtualenv command in docs

### ISSUE THREAD

**Issue by cbartle891** [martinthomson/i-d-template#233]
doc/SETUP.md includes the following command: `virtualenv --no-site-packages venv`. However, `--no-site-packages` has been removed from virtualenv, as it's now default behavior. Using the flag in the latest virtualenv version (currently 20.0.27) results in an 'unrecognized arguments' error.

https://virtualenv.pypa.io/en/legacy/reference.html#cmdoption-no-site-packages

**Comment by martinthomson** [comment]
Linked this one too late.  Closing manually.
