### ISSUE TITLE
xslt now seems to require rfc2629-no-doctype.xslt to be in lib/

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#235]
see https://app.circleci.com/pipelines/github/httpwg/http-extensions/465/workflows/8dcfbbb4-29e2-4186-84c5-8ea738c5aeea/jobs/3519

needs to be transformed to 1.0.

**Comment by mnot** [comment]
Hm, still getting 

> warning: failed to load external entity "lib/rfc2629-no-doctype.xslt"

**Comment by martinthomson** [comment]
```
~/code/http-extensions master
$ make
xsltproc lib/rfc2629xslt/to-1.0-xslt.xslt lib/rfc2629xslt/rfc2629-no-doctype.xslt > lib/rfc2629-no-doctype.xslt
xsltproc lib/rfc2629xslt/to-1.0-xslt.xslt lib/rfc2629xslt/clean-for-DTD.xslt > lib/clean-for-DTD.xslt
xsltproc lib/rfc2629xslt/to-1.0-xslt.xslt lib/rfc2629xslt/rfc2629.xslt > lib/rfc2629.xslt
cat draft-ietf-httpbis-bcp56bis.md  | kramdown-rfc2629 --v3 | lib/add-note.py > draft-ietf-httpbis-bcp56bis.xml
```
WFM

Is is possible that your checkout of the XSLT repo predates `lib/rfc2629.xslt`, such that the makefile believes that it is not necessary to update it?

**Comment by mnot** [comment]
It was the `main` vs `master` issue
