### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#241]
https://travis-ci.org/github/cbor-wg/CBORbis/builds/730099178

(trying to update to current version after smooth sailing with Nov 2019 version for 10 months)

**Comment by martinthomson** [comment]
We can thank https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/554 for this.

I have tried to add a workaround, but it doesn't appear to have fixed the issue.  (I added `pip install python-magic`, which works locally in a virtualenv.)

**Comment by martinthomson** [comment]
Hmm, this is not the problem.  I have a solution, but it is unpleasant.  I'll get a fix prepared ASAP though.

**Comment by martinthomson** [comment]
@cabo, has this sorted itself out?  https://travis-ci.org/github/cbor-wg/CBORbis looks clean (aside from warnings about using an orphaned branch).

**Comment by cabo** [comment]
Indeed, apparently it now works.  Not sure whether xml2rfc fixes are part of that.

**Comment by cabo** [comment]
Just did another random rebuild, https://travis-ci.org/github/core-wg/stateless -- maybe unrelated observation:

```
Traceback (most recent call last):
  File "lib/archive_repo.py", line 11, in <module>
    import dateutil.parser as dp
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by martinthomson** [comment]
I haven't dealt with the xml2rfc problem: it's a consequence of taking a dependency on a module that installs successfully when its own (native) dependencies aren't satisfied.

The build error there is the travis image not including python[3]-dateutil.  I really need to copy your hack from the cborbis to use the docker image with travis: their images lag too much to deal with.
