### ISSUE TITLE
mmark isn't available on 20.04

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/i-d-template#242]
For $reasons I need to move to Ubuntu 20.04 earlier than planned.  The mmark package isn't available there.

@miekg, do you have plans to make a pre-build package available somehow, or are you not involved in that process?  I would like to support this package, but it's a little tricky to do so if it requires building.  Is https://github.com/mmarkdown/mmark/releases your current best option?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[martinthomson/i-d-template] mmark ..." ]
>For $reasons I need to move to Ubuntu 20.04 earlier than planned. The mmark
>package isn't available there.
>
>@miekg, do you have plans to make a pre-build package available somehow, or are
>you not involved in that process? I would like to support this package, but
>it's a little tricky to do so if it requires building. Is https://github.com/
>mmarkdown/mmark/releases your current best option?

I'm not involved with packaging for ubuntu. Yep the releases on github is what there
currently exists. Just putting the binary in a ~/bin should do the trick.

/Miek

--
Miek Gieben

**Comment by martinthomson** [comment]
Thanks!  I'll try that out.
