### ISSUE TITLE
gh-pages generator seems to be missing dateutil.py

### ISSUE THREAD

**Issue by mcr** [martinthomson/i-d-template#244]
I am getting this from a travis-ci build:

    The command "make" exited with 0.
    2.51s$ make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues  
    git fetch -qf origin gh-pages:gh-pages
    Traceback (most recent call last): 
      File "lib/archive_repo.py", line 11, in <module>
       import dateutil.parser as dp  
    ModuleNotFoundError: No module named 'dateutil'

I am trying add python-is-python3, python3-dateutil and move from trusty to bionic.
And we'll see.  Maybe this is a FAQ.

**Comment by mcr** [comment]
It seems to be pulling in dateutil:

    Preparing to unpack .../python3-dateutil_2.6.1-1_all.deb ...
    Unpacking python3-dateutil (2.6.1-1) ...

**Comment by martinthomson** [comment]
Carsten pointed the same thing out.  I can't explain it.  This clearly installs the python3 package, the script definitely runs python3, and nothing else seems off.  You aren't using the docker image-based build I recently added, which is the only thing that is different here.

Once again, travis seems to be the source of more strangeness.

**Comment by mcr** [comment]
> Once again, travis seems to be the source of more strangeness.

yeah. A long time ago, one could get a VM that matched their environment to debug, but no longer.

**Comment by martinthomson** [comment]
I'm going to call this resolved (though we got a reprisal of this issue again as a result of me messing with images, see #264).  I do have some more work to do regarding testing though, clearly.
