### ISSUE TITLE
build-index.sh

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#246]
I'm starting to use a jekyll remote template to pull together the look and feel of how httpwg repos are presented, and it's going well.

However, the `index.html` created by i-d-template poses two problems:

1. It conflicts with taking up the README file as the default for the repo, which is sometimes desirable.
2. It's in HTML, not markdown, so it's more difficult to style (e.g., adding a navigation bar).

I think this could be addressed by:

1. Making the name of the file configurable
2. Allowing optional markdown output instead of HTML

@martinthomson if you're amenable I suspect you'd be more efficient at (1); I can take a stab at (2), although hooking in the control mechanism might be better done by you. WDYT?

**Comment by mnot** [comment]
Oh, this would imply that the branch written to (and presumably the directory) would be configurable too.

**Comment by martinthomson** [comment]
@mnot - is this now satisfactory?

**Comment by mnot** [comment]
Hmm. I've set `MD_INDEX := true`, but it still generates `index.html`, which overrides the markdown for index views.

**Comment by martinthomson** [comment]
Ah, something got lost somewhere.  Try `INDEX_FORMAT := md` instead.

**Comment by mnot** [comment]
Seems to work fine, thanks! I've got it going for `http-extensions` and `http2-spec` now.

@LPardue if you want https://quicwg.org/base-drafts/ to be prettier (see e.g., https://httpwg.org/http-extensions/ ) try this; you'll need to have a theme repo (like https://github.com/httpwg/theme) and point to it in `_config.yml`.
