### ISSUE TITLE
.gitignore for /lib needed on gh-pages

### ISSUE THREAD

**Issue by larseggert** [martinthomson/i-d-template#25]
`make gh-pages` was failing for me due to untracked files under `lib/`. I added a `.gitignore` file with an entry to `lib/` on the `gh-pages` branch in order to suppress that error. This fixed the `make`.

(Or maybe this isn't needed and I did something wrong? First time I'm using this toolchain.)

**Comment by martinthomson** [comment]
Already fixed, I think.  I didn't expect that anyone would actually notice that.  Try `git -C lib pull origin master` to fix it.

**Comment by martinthomson** [comment]
Oh, that fix isn't going to work for people who setup the repo at the wrong time.  It only includes `lib` during the setup.  You'll have to add that yourself.

Fixed in 1277c6167df003a87
