### ISSUE TITLE
GitHub pages changes if 'Experimental Web Platform Features' flag is enabled on Chrome

### ISSUE THREAD

**Issue by amtunlimited** [martinthomson/i-d-template#252]
The article text gets smaller, apparently the same size as the sidebar text. I don't know if it's a bug w/ your CSS or Chrome, but I thought it might be work pointing out.

Currently on 86.0.4240.198 Stable

Before:
![image](https://user-images.githubusercontent.com/1744426/99683689-9fb22500-2a4e-11eb-86ad-c9b142526a7c.png)

After:
![image](https://user-images.githubusercontent.com/1744426/99683422-54981200-2a4e-11eb-83bc-474bde93f3c3.png)

**Comment by martinthomson** [comment]
Does the computed value of font-size change?  I'm also curious as to which feature is causing this.

Of course, I will staunchly stand by the law of the Internet here and say that fault accrues to the party that changed last.  It seems fairly obvious that this is Chrome.  This uses very simple CSS for font sizes, no percentages or relative sizes, just *`n`*`px`.

**Comment by martinthomson** [comment]
Closing this. It seems totally fine on mainline Chrome (with the flag flipped, even).  Those who enable experimental flags in browsers are taking their lives into their own hands.
