### ISSUE TITLE
GitHub page not active

### ISSUE THREAD

**Issue by maifeeulasad** [martinthomson/i-d-template#255]
I tried to visit : https://martinthomson.github.io/i-d-template/

But there was no web-page available. But a [gh-pages](https://github.com/martinthomson/i-d-template/tree/gh-pages) exists. 

I guess it is not correctly configured in : **Settings -> GitHub Pages -> Source**.

*I'm not even sure, if this is supposed to exist or not*

**Comment by martinthomson** [comment]
This is intentional. There is some content being served from this URL, but there isn't a web site there.

I'll keep this open to track putting some content there, even if it is just a redirect to documentation on the repo proper.

**Comment by martinthomson** [comment]
Content is up.  Just a simple redirect.
