### ISSUE TITLE
Discussion - use submodule over clone

### ISSUE THREAD

**Issue by maifeeulasad** [martinthomson/i-d-template#257]
One of the crucial command on using this template repository is : 
```
git clone https://github.com/martinthomson/i-d-template lib
```
But wouldn't it be more cool if we use sub-module, like : 
```
git submodule add https://github.com/martinthomson/i-d-template
```

**Comment by maifeeulasad** [comment]
If it is cool, can I get assigned to this ?

**Comment by martinthomson** [comment]
That is already documented as an option here: https://github.com/martinthomson/i-d-template/blob/main/doc/REPO.md

Of course, then you have to deal with all the drawbacks of submodules.
