### ISSUE TITLE
Versioning info needs a bit more text at least

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#261]
From https://github.com/martinthomson/i-d-template/blob/main/doc/REPO.md:
`
Edit the draft so that it has both a title and the correct name. These tools use the -latest suffix in place of the usual number ('-00', or '-08'). The number is generated automatically when you use make submit.
`

So I should name the file `draft-ietf-unicorn-protocol-latest.{md,xml}` ?

Can the setup check to see if the docname or docName ends with -latest?  And that the filename does?

**Comment by richsalz** [comment]
Of course, I got the filename requirement backwards.  *Don't* end with -latest, and therefore  check in "make setup" that it doesn't.

**Comment by martinthomson** [comment]
First step is to fix the documentation.  Then I'll see about the validation (which is a good idea).

**Comment by martinthomson** [comment]
There was already validation, but it is easy to miss in the noise.  Elevating that to an error is probably the best way.
