### ISSUE TITLE
"ModuleNotFoundError: No module named 'dateutil'"

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#264]
Using stock lib, https://github.com/richsalz/draft-rsalz-update-registries/runs/1859490185?check_suite_focus=true

**Comment by richsalz** [comment]
also https://github.com/richsalz/draft-rsalz-use-san/runs/1859436279?check_suite_focus=true

**Comment by martinthomson** [comment]
Yeah, sorry about that.  A package went missing.  I've pushed a change that restores it.

**Comment by richsalz** [comment]
no prob.  i usually think i'm doing something wrong :)

**Comment by martinthomson** [comment]
Once I can load the archival script from pypi, this problem won't happen.  For now, it's fixed in the images.
