### ISSUE TITLE
Docker doesn't run on Travis

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#267]
I'm not sure I'll need to cope with Travis for much longer, so I offer this as a FYI:

https://travis-ci.org/github/core-wg/senml-versions/builds/758663185

... says:

```
Error response from daemon: Container 29b164d69d3b345d6db10e7fe0a065eba8ee7122b101bf985adcd0da66a4b2ff is not running
```
after just having started it.

**Comment by martinthomson** [comment]
This looks to have been resolved based on the [latest build](https://travis-ci.org/github/core-wg/senml-versions/builds/759882918) in that repo, even if that build is broken for other reasons.  @cabo, ok to close?
