### ISSUE TITLE
Can we archive github discussions?

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#268]
...as in <https://github.com/WebOfTrustInfo/Community/discussions>

Like we do issues and pull requests in <https://github.com/martinthomson/i-d-template/blob/main/template/.github/workflows/archive.yml>?

Background:

<https://mailarchive.ietf.org/arch/msg/jsonpath/z2a4Vl_aV-yw0Igk8YTTWd7fjVY>

**Comment by MikeBishop** [comment]
Seems like the appropriate interfaces have been added to the GitHub API; I don't see why not.  I'll take a look at adding the query next week.

**Comment by martinthomson** [comment]
Seems like Mike has this in hand.
