### ISSUE TITLE
why make version 4

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#27]
v 3.81 is bundled with my ubuntu system.  is v4 really needed?

**Comment by martinthomson** [comment]
Actually, the only version I've had problems with is the one that ships on
the Mac.

**Comment by richsalz** [comment]
3.81 works fine for me, by editing the '3' in compat.mk to be '4'. :)
What's the best way to handle this?

**Comment by martinthomson** [comment]
I'll fix the warning so that only Mac users see it.

**Comment by martinthomson** [comment]
Fixed in 98bdbd7
