### ISSUE TITLE
unable to determine default branch

### ISSUE THREAD

**Issue by chucklever** [martinthomson/i-d-template#273]
I've attempted to change my default repo branch from "master" to "main". Now I see several "unable to determine default branch" warnings on every build:

```
anon-dhcp-153:nfs-ulb-v2 cel$ make
warning: lib/default-branch.py unable to determine default branch
xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://datatracker.ietf.org/doc/html/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/cel/.cache/xml2rfc draft-ietf-nfsv4-nfs-ulb-v2.xml -o draft-ietf-nfsv4-nfs-ulb-v2.txt --text --no-pagination
warning: lib/default-branch.py unable to determine default branch
draft-ietf-nfsv4-nfs-ulb-v2.xml(19): Warning: The 'docName' attribute of the <rfc/> element should have a revision number as the last component: docName="draft-foo-bar-02".
xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://datatracker.ietf.org/doc/html/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/cel/.cache/xml2rfc --css=lib/v3.css --metadata-js-url=/dev/null draft-ietf-nfsv4-nfs-ulb-v2.xml -o draft-ietf-nfsv4-nfs-ulb-v2.html --html
warning: lib/default-branch.py unable to determine default branch
draft-ietf-nfsv4-nfs-ulb-v2.xml(19): Warning: The 'docName' attribute of the <rfc/> element should have a revision number as the last component: docName="draft-foo-bar-02".
anon-dhcp-153:nfs-ulb-v2 cel$
```

**Comment by martinthomson** [comment]
This is one of the more messy parts of a transition.

The general fix is to run this:

```
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

This creates a `HEAD` alias for the origin that the script can use to identify `main` properly.  I might need to add some warnings about that.

**Comment by chucklever** [comment]
> The general fix is to run this:
> 
> ```
> git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
> ```

Confirming that this command worked for me. Thanks!

**Comment by martinthomson** [comment]
Ahh, that's a problem I can help fix now.  The problem there is that we need to use the GitHub API to determine this (because the GitHub checkout action doesn't place the HEAD alias. 05a46d4 includes that change.  Basically it looks like this:

```diff
     - name: "Build Drafts"
       uses: martinthomson/i-d-template@v1
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
```

You will need to update your `.github/workflows/ghpages.yml` to see this working.

**Comment by cabo** [comment]
Indeed seems to work.

https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/100/checks?check_run_id=2799827652

**Comment by martinthomson** [comment]
I've modified the default-branch script to magically fix the issue when it can.  This isn't ideal, but it does cut down on noise (and makes things marginally faster).
