### ISSUE TITLE
Deleting XML that we are supposed to submit to the IETF?

### ISSUE THREAD

**Issue by SpencerDawkins** [martinthomson/i-d-template#280]
@martinthomson, thank you for doing this work (which I've been using for several years, without ever thinking to say that - sorry!). 

I'm using https://github.com/martinthomson/i-d-template/ in several repos, and I noticed that the version of make I'm using still deletes the XML after creating .TXT and .HTML. 

Is that the way you think it works? If I'm doing this wrong, please let me know. 

If not, and if XML is the canonical format for the RFC Editor, is it possible to leave the XML when make finishes, so I can submit that?

**Comment by MikeBishop** [comment]
When you're ready to submit, do a `make submit` which generates the txt and xml files for you to upload.  Or use `make upload`, which uploads them to Datatracker for you.  Or tag the commit and push tags to the GitHub repo, and the C-I will run `make upload` on your behalf.

**Comment by MikeBishop** [comment]
(Note that `make submit` looks at the tags in the repo to determine which draft version number to assign the new files.  If you haven't been doing that, you might need to add some historical tags to your repo.)

**Comment by SpencerDawkins** [comment]
@MikeBishop, thank you so much for your help!

I was sure I was missing something ...

**Comment by martinthomson** [comment]
I don't think that `make submit` is what we want, long term.  I've deprecated it.  (It's still there as `make next`.)

The best way to do this is to either tag and push (and have CI submit for you).  Failing that, tag and `make upload` as Mike points out.  Backing up with `make next` always exists, but arguably what you really want there is to tag the draft and then do `make draft-dawkins-foo-protocol-03.xml`.
