### ISSUE TITLE
Enable inclusive terminology CI for new repos

### ISSUE THREAD

**Issue by larseggert** [martinthomson/i-d-template#283]
It'd be neat if the [In Solidarity bot](https://github.com/apps/in-solidarity) was enabled for new I-D repos, maybe with the IETF-inspired config at https://github.com/NTAP/isb-ietf-config.

**Comment by martinthomson** [comment]
Lars, is there an actions-based flow for this?  Installing the bot makes the setup process manual.  At that point, the instructions you have are not that much more onerous and automating them doesn't add a whole lot.  Given that adding a `.github` repo means that it's once per user, that might be preferable.

If this were an action then I could make this have effectively zero setup cost. I could also check for the global installation to avoid doubling the work.

**Comment by larseggert** [comment]
Let me check. I guess you mean "can we add a YAML script instead of needing someone to manually enable the bot"?

**Comment by martinthomson** [comment]
Yeah, that's it.  Presumably there is code for this somewhere; can we just run that as part of a build?

**Comment by larseggert** [comment]
Not sure if this is easily possible with the bot source. I opened https://github.com/jpoehnelt/in-solidarity-bot/issues/271.

I have some code in https://github.com/larseggert/ietf-reviewtool/blob/main/ietf_reviewtool/ietf_reviewtool.py#L1181-L1244 that uses the [config file](https://github.com/NTAP/isb-ietf-config/blob/main/.github/in-solidarity.yml) but not the rest of the actual bot to generate issue warnings, maybe it would be easier to package that in some form.

**Comment by larseggert** [comment]
In order to run the bot, it is sufficient to create a file, such as `.github/in-solidarity.yml`, with the following content:
```
# use configuration from https://github.com/NTAP/isb-ietf-config
_extends: NTAP/isb-ietf-config
```
This would then always use the current upstream config of the bot.

**Comment by martinthomson** [comment]
Just so we're clear, you need to also enable the app in order to use the configuration, right?

A PR would be good.  I would need one here as well (template/.github/in-solidarity.yml and the list of files in setup.mk).  Even if the bot still needs to be enabled, lowering friction is fine.

**Comment by martinthomson** [comment]
@larseggert, have you considered moving the config to the ietf/terminology repo? That would be much easier to use.

**Comment by larseggert** [comment]
I have had a ticket open on this (https://github.com/ietf/terminology/issues/14) but no opinions were expressed on it yet.

**Comment by larseggert** [comment]
The bot config now lives at https://github.com/ietf/terminology, see the instructions to enable it there.

**Comment by martinthomson** [comment]
It looks like the right answer here is an org-level .github repository with the configuration.  The bot requires a process for enabling it, which is done on a per-organization basis, so having a per-organization configuration is ideal.
