### ISSUE TITLE
index.html generation (for multiple documents) on Travis or OS X

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#30]
The "define INDEX_HTML =" part of ghpages.mk does not seem to work with Travis' make.  It appears to leave an empty variable, so we get (https://travis-ci.org/core-wg/yang-cbor) something like

```
echo -e '' >index.html
```

Workaround: `make ghpages` and manually push the `gh-pages` branch on the laptop.

Also, neither Travis' nor OS X's echo as called from make supports -e, so the -e option gets dumped literally, as can be seen in https://core-wg.github.io/yang-cbor/ (more of an esthetic problem here).  (The result of both problems is that for Travis, the entire contents of index.html will be `-e`.)

**Comment by martinthomson** [comment]
I hope that fixes the problem for you, sorry about the delay.

**Comment by cabo** [comment]
Thank you, that now works well!
