### ISSUE TITLE
Make branch history tunable

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#303]
... currently 30 days; would be good to make this configurable (as discussed).

**Comment by martinthomson** [comment]
New variables added:

GHPAGES_COMMIT_TTL is the number of days worth of commits to keep on the gh-pages branch.

GHPAGES_BRANCH_TTL is the number of days to retain a directory on gh-pages after the corresponding branch has been deleted. This is measured from the last change.

Both default to 30.  Any number should be OK.  I can't vouch for very large numbers, but 100000000 seems to work fine (at least on my machine).

**Comment by MikeBishop** [comment]
It works fine so long as you don't actually have history that old, anyway!  We originally added this feature because the history of `gh-pages` had become the majority of a very large repo.  275k years of history will get... sizeable if changes are frequent.
