### ISSUE TITLE
Upgrade xml2rfc used by github action

### ISSUE THREAD

**Issue by glyn** [martinthomson/i-d-template#312]
v3.10.0 of xml2rfc was recently [announced](https://mailarchive.ietf.org/arch/msg/xml2rfc/IuHZtvu_oAORLdgq-wLSSXObYfE/). It includes several improvements and fixes, at least one of which I'd like to pick up.

Please could you upgrade xml2rfc used by the i-d-template github action and tag the action so [we](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base) and others can use it.

**Comment by martinthomson** [comment]
Give it about 15 minutes and it should be available.  A build is running now.  (It's almost midnight, so if the build fails, feel free to reopen this.)

**Comment by cabo** [comment]
Not sure I need to bump this for 3.11.1 (and 1.5.15, for that matter).
