### ISSUE TITLE
Add documentation how to update template and add a "Discussion venues" section from an old repo

### ISSUE THREAD

**Issue by theri** [martinthomson/i-d-template#323]
On a draft that was started way back before the "Discussion venues" section feature existed, I was asked to add such a section, and it was not easy to figure out how to do it, starting from an outdated template repo etc.

I finally managed to do it using the [steps described in this PR in the document repo](https://github.com/panrg/path-properties/pull/65), and I hope I didn't break anything in the process. 
I suppose rerunning `make -f lib/setup.mk` on an existing document shouldn't break anything, as it's mentioned at the end of [REPO.md](https://github.com/martinthomson/i-d-template/blob/main/doc/REPO.md#regenerating-readmemd), but it took me a while to figure out that that's what I needed to do. I guess running this command is not just for updating README.md anymore...

I can imagine other people might run into similar problems.
So I suggest adding some steps to either REPO.md or SETUP.md or maybe a different file, which explain how to update an outdated repo.

(I am also curious if updating the template repo and re-running lib/setup.mk led to other changes that I am not yet aware of?)

**Comment by martinthomson** [comment]
I've started documenting these features at https://github.com/martinthomson/i-d-template/blob/main/doc/UPDATE.md

I hope that helps a little.
