### ISSUE TITLE
failed 'publish to datatracker' run

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#324]
https://github.com/richsalz/draft-rsalz-update-registries/runs/6063392873?check_suite_focus=true

**Comment by letmaik** [comment]
Same here: https://github.com/ietf-scitt/draft-birkholz-scitt-receipts/runs/6080128148?check_suite_focus=true

**Comment by larseggert** [comment]
See https://github.com/martinthomson/i-d-template/pull/325

**Comment by martinthomson** [comment]
Fixed by #325.
