### ISSUE TITLE
Job summaries

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#330]
[This](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) seems promising. Most obvious places to use it:

- [x] in `ghpages.yml` "Build Drafts"
- [ ] in `ghpages.yml` "Update GitHub Pages"
- [x] in `publish.yml` "Build Drafts"
- [ ] in `publish.yml` "Upload to Datatracker"

**Comment by martinthomson** [comment]
Indeed.  The trick being to provide a useful summary of what happened without overdoing it.

For building drafts, it seems like we might report on the number of drafts that were successfully built, which drafts did not successfully build, plus the number of errors that were produced.  Counting or reporting on errors requires a little post processing, but the other items seem fairly trivial to produce and could provide some value.  

Ideally we could reproduce some of the error logs, but that might require some engineering.  I'm thinking a wrapper script that calls `exec` when the variable isn't set, but captures and reformats output when the task fails and output is produced.

**Comment by martinthomson** [comment]
Here is what I have so far.  I need to build out the upload pieces, but this is the main event:

## Build Failed

✅ draft-ietf-quic-http

✅ draft-ietf-quic-qpack

✅ rfc8999

<details><summary>❌ rfc9000: step 'nl' failed</summary>

```
rfc9000.md has no newline on the last line
```
</details>

<details><summary>❌ rfc9000: step 'ws' failed</summary>

```
rfc9000.md contains trailing whitespace
```
</details>

✅ rfc9001

✅ rfc9002

**Comment by mnot** [comment]
good start
