### ISSUE TITLE
Don't rely on user-installed tools

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#334]
For command-line usage, it'd be more reliable to set up a .venv for the Python tools, and for Ruby I think the equivalent is RVM.

For Python, I highly recommend:
  https://github.com/sio/Makefile.venv

**Comment by martinthomson** [comment]
Most of these changes are on a branch (mnot-334).  I'm fairly confident in them now (I've been using them myself).  However, given the size of the changes and the upcoming IETF meeting, I'm going to wait until the submission deadline passes to land them.

**Comment by mnot** [comment]
This can be closed, no?

**Comment by martinthomson** [comment]
Yes, I think so.  Thanks for the reminder.
