### ISSUE TITLE
Web-Based GH Directions

### ISSUE THREAD

**Issue by jlivingood** [martinthomson/i-d-template#339]
It'd also be great to include some easy directions for those of us that prefer to use the web-based UI for GitHub. This may also be one of the key workflows for new IETF contributors.

**Comment by martinthomson** [comment]
@jlivingood, let me know how https://github.com/martinthomson/i-d-template/blob/main/doc/WEB.md works out for you.  It's a little rough, but I think that I got most of the important stuff.
