### ISSUE TITLE
installing via Gemfile does not work for cddl and cbor-diag

### ISSUE THREAD

**Issue by thomas-fossati** [martinthomson/i-d-template#344]
I am trying to install `cddl` and `cbor-diag` via Gemfile:

```shell
~/draft-ietf-rats-corim $ cat Gemfile
source 'https://rubygems.org'

gem 'cddl'
gem 'cbor-diag'
```

which fails in the "Build Drafts" stage [like this](https://github.com/ietf-rats-wg/draft-ietf-rats-corim/runs/8146179396).

I have tried using the "mega" image but the result is the same:
```
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.
```

**Comment by cabo** [comment]
Can you try adding json-pure?

**Comment by thomas-fossati** [comment]
> Can you try adding json-pure?

Thanks for the hint Carsten.  Unfortunately it failed in the same way: https://github.com/ietf-rats-wg/draft-ietf-rats-corim/runs/8174835426

**Comment by martinthomson** [comment]
@cabo, this seems to be the same problem we have with kramdown-rfc, which we fixed by switching the dependency in kramdown-rfc to json_pure.  Maybe you can try doing that for both of these gems too.

**Comment by thomas-fossati** [comment]
Thanks Carsten for the fix!  For reference, the Gemfile with the versioning info that worked for me is copied below.  (Note that if the environment is pristine, the explicit versions are not necessary.)

```
source 'https://rubygems.org'

gem 'json_pure'
gem 'cddl', '>=0.9.1'
gem 'cbor-diag', '>=0.8.1'
```

**Comment by martinthomson** [comment]
The log shows that cddl 0.12.11 is being installed.  @cabo, do you know if there is anything in that release that would cause a cddl binary not to land on the path?  (The path will include the `.gems/bin` directory that should be created by bundle installation.)

**Comment by martinthomson** [comment]
Oh, I think that I know what is going on now.  It's a nasty one.  The nested `Makefile` that you are using means that the PWD for the execution of scripts from `make` won't pick up the `$PATH` entry, because that uses a relative path.  The compatibility hazards around getting absolute paths turned out to be a real problem for some people due to a confluence of issues.

In short, you can't rely on the automatic install of gems for commands run in a different `Makefile`.

**Comment by nedmsmith** [comment]
> The best I can offer is a suggestion to move your cddl invocations to the top-level Makefile.

Other repos seem to work that do similar nesting of make files: e.g.: https://github.com/nedmsmith/draft-cds-rats-intel-corim-profile/blob/main/cddl/Makefile

Corim has been doing similar stuff for quite a while. I may be in advertantly shooting myself in the foot in https://github.com/nedmsmith/draft-smith-satp-vlei-binding/blob/main/cddl/Makefile. 

But moving everything into a top level makefile for both repos doesn't seem to make sense if one is working and the other isn't.

**Comment by nedmsmith** [comment]
Thanks for the attention. I resolved the issue - had to do with LIB_DIR not being set correctly.

**Comment by martinthomson** [comment]
Good news.

BTW, this will breakdown if you somehow end up with a space in a directory name above your repository (i.e., "/home/me/some path/repository" as the root of your repository).  The obvious answer there is "don't do that", but it's worth noting the limits of what is possible with `make`.
