### ISSUE TITLE
is the "mega" image still maintained?

### ISSUE THREAD

**Issue by thomas-fossati** [martinthomson/i-d-template#345]
The documentation mentions a ["mega"](https://github.com/martinthomson/i-d-template/blob/main/doc/LINTING.md#using-the-mega-image-in-ci) image. Since it builds FROM the "normal" image, it means it should be rebuilt at the same pace. However, it looks like it's been a while since it was last pushed to the registry. So I guess my question is whether "mega" is actively maintained or it was just an experiment that is not active anymore?

**Comment by martinthomson** [comment]
You can find it at https://github.com/martinthomson/i-d-template/pkgs/container/i-d-template-math

It's two days old according to that page (which is as fresh as the main one).
