### ISSUE TITLE
Adding extra Ruby gems breaks the `ghpages` target

### ISSUE THREAD

**Issue by thomas-fossati** [martinthomson/i-d-template#346]
We are adding [three extra gems](https://github.com/ietf-rats-wg/draft-ietf-rats-corim/blob/main/Gemfile) as part of [our build](https://github.com/ietf-rats-wg/draft-ietf-rats-corim/blob/main/Makefile), and the "Update Editor's Copy" workflow fails like this:

```
> Update GitHub Pages
[...]
touch: cannot touch '/tmp/.gems/.i-d-template.opt': No such file or directory
make[1]: *** [lib/deps.mk:99: /tmp/.gems/.i-d-template.opt] Error 1
mkdir -p /tmp/ghpages86/draft-ietf-rats-corim-00
make[1]: Target 'ghpages' not remade because of errors.
make: *** [lib/ghpages.mk:121: ghpages] Error 2
```

For the complete trace, see https://github.com/ietf-rats-wg/draft-ietf-rats-corim/runs/8202229211

**Comment by thomas-fossati** [comment]
it looks like there is a missing `mkdir -p $(BUNDLE_PATH)` before [lib/deps.mk:99](https://github.com/martinthomson/i-d-template/blob/b1aedf2b776dc024179620d37211ea766e36adfa/deps.mk#L99)

**Comment by martinthomson** [comment]
OK, I think that I've fixed this up, so you should be able to run another build.  I'll send you a pull request (and maybe a few others who might have similar issues).

**Comment by martinthomson** [comment]
Closing this.  Let me know if anything doesn't work out for you.

**Comment by thomas-fossati** [comment]
> Closing this. Let me know if anything doesn't work out for you.

It worked.  Thanks a lot!
