### ISSUE TITLE
CODEOWNERS foul-up

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/i-d-template#348]
See https://github.com/httpwg/http-extensions/pull/2245#discussion_r968472506

**Comment by martinthomson** [comment]
No idea what happened here.  It worked for me.  Might be a Mac thing.

**Comment by LPardue** [comment]
If you're implying that was using a mac, then I can clarify that I did not :D

**Comment by martinthomson** [comment]
Worked it out!

There were some .xml files floating around (the http-extensions repo includes `.SECONDARY: $(drafts_xml)`, which is unusual).  Those are built and whatnot (which is sort of fine, sort of not, but not my problem either way).

The code that generates CODEOWNERS found those and tried to create a line because those files are listed in `$(drafts)`.  But in generating the line, I use `git ls-files` to find which file extension is checked in, because it's easier than tracking that all the way through (the author name is lifted from the .xml file).  When the file didn't exist, I printed the empty string, then listed the authors.  Inevitably, that didn't work out very well.

The fix is to skip files that aren't checked in.  Simple really.
