### ISSUE TITLE
Clarify documentation about recovering I-D template lib environment

### ISSUE THREAD

**Issue by gloinul** [martinthomson/i-d-template#349]
I have had two different failures with the build programs not working. 

The first the build simply stopped working after updating some parts of the machine environments resulting in failure to load xml2rfc.run module for example. 

In trying to determine if this was an issue with my general machine and its installation, or if it was the I-D-template build. Thus, I cloned a new copy and it worked. Then I tried moving the repository which resulted in broken links. 

I think it would be good if the documentation was clearer what one should do in these cases. I realised that one simple way of dealing with it is to simply delete the ./lib directory. If there are other way that may work with this, it would be good. But "make update" or "make update-deps" do not work for this.

**Comment by martinthomson** [comment]
I've added some text to the [TIPS](https://github.com/martinthomson/i-d-template/blob/main/doc/TIPS.md).
