### ISSUE TITLE
No rule to make targetr `Makefile'

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#35]
```
; ls
LICENSE  README.md  draft-rsalz-drbg-speck-wap-wep.md  lib
; cat .gitmodules
[submodule "lib"]
        path = lib
        url = https://github.com/martinthomson/i-d-template
; git -C lib pull origin master
From https://github.com/martinthomson/i-d-template
 * branch            master     -> FETCH_HEAD
Already up-to-date.
; make -f lib/setup.mk
make: *** No rule to make target `Makefile', needed by `setup-readme'.  Stop.
        exit 2
;
```

**Comment by martinthomson** [comment]
Fantastic.  I rely on some fairly make-foo for setting that up, something that I've learned hurts.  Still, you aren't on OS X are you?

```sh
; make -q -p -f lib/setup.mk  | grep -A 6 '^Makefile:'
Makefile: lib/template/Makefile
#  Implicit rule search has not been done.
#  Last modified 2016-03-23 15:08:23.230951234
#  File has been updated.
#  Successfully updated.
#  recipe to execute (from 'lib/setup.mk', line 41):
	cp $< $@
```

BTW, I don't use submodules any more, a clone is easier (a symlink to a clone is better)

**Comment by richsalz** [comment]
OS/X, the poor man's windows? :)  No, pretty stock linux.

; ; make -q -p -f lib/setup.mk  | grep -A 6 '^Makefile:'
make: *** No rule to make target `CONTRIBUTING.md', needed by `setup-readme'.  Stop.
Makefile:
#  Implicit rule search has been done.
#  Last modified 2016-03-22 22:46:29.871241316
#  File has been updated.
#  Successfully updated.
# variable set hash-table stats:
# Load=0/32=0%, Rehash=0, Collisions=0/0=0%
;

I'll follow whatever instructions are in your README :)

**Comment by martinthomson** [comment]
Hmm, I've a new version available.  Maybe you can update*  It's got a lot more checking to see if you have everything just so.  It also doesn't do the strange templating stuff for setup, which should make this more accessible (I have the rules for `make submit` on my todo list).

* or just turn the lib directory into a clone.

**Comment by richsalz** [comment]
```
... stuff elided ...
git commit -m "Setup repository for draft-rsalz-drbg-speck-wap-wep"
[master 086cecc] Setup repository for draft-rsalz-drbg-speck-wap-wep
 6 files changed, 213 insertions(+), 2 deletions(-)
 create mode 100644 .travis.yml
 create mode 100644 CONTRIBUTING.md
 create mode 100644 Makefile
 rewrite README.md (100%)
 create mode 100644 circle.yml
Error: Uncommitted changes on branch
make: *** [setup-ghpages] Error 1
rm draft-rsalz-drbg-speck-wap-wep.xml
        exit 2
```

**Comment by martinthomson** [comment]
Thanks Rich, I think that you are OK here, but in a sad state.

I think that you can manually do the steps I just added and you will be ok:

```sh
echo lib > .gitignore
echo .refcache >> .gitignore
git add .gitignore
git commit -m "Ignoring stuff"
git checkout master
```

BTW, I've almost reached the point now where I've stopped wondering why this all works for me but not (almost) everyone else.

**Comment by richsalz** [comment]
Script once, debug everywhere.

You wrote "git checkout master" I think you meant git push.  When I did that, I see:
```
; g status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   lib (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        draft-rsalz-drbg-speck-wap-wep.html
        draft-rsalz-drbg-speck-wap-wep.txt
        draft-rsalz-drbg-speck-wap-wep.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by martinthomson** [comment]
I did mean `checkout`.  But your problem is that there are intermediate files left lying around.  My problem was in misunderstanding what `git rm` does: https://github.com/martinthomson/i-d-template/blob/master/setup.mk#L93

I think that all you need to do is run `git clean -qfdX && git checkout master` and you will be right.  The push appears to have worked.

**Comment by richsalz** [comment]
shrug.  still get lib with new commits.  F it.  thanks.
