### ISSUE TITLE
feat: v1m doesn't seem to have asciitex

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#352]

**Comment by cabo** [comment]
https://github.com/cbor-wg/time-tag/actions/runs/3186288820/jobs/5196724680

**Comment by martinthomson** [comment]
That log uses `@v1` and not `@v1m`.  https://github.com/cbor-wg/time-tag/blob/36cbef2362f29d4e0d6ffc4591cb4e9371abd4c8/.github/workflows/ghpages.yml#L47

I see that you changed a different YAML file.  Try updating all of them.

**Comment by cabo** [comment]
Indeed, that was it.  Did a global substitute and now it works.  Thank you!
