### ISSUE TITLE
Setup action fails with vague error

### ISSUE THREAD

**Issue by aaronpk** [martinthomson/i-d-template#356]
Hi! I just set this up on a new repository and I'm getting an error trying to publish a version to datatracker. The draft built fine in GitHub Pages, but the action that publishes to datatracker is giving an error:

<a href="https://github.com/oauth-wg/oauth-cross-device-security/actions/runs/3642937420/jobs/6150609338"><img width="855" alt="image" src="https://user-images.githubusercontent.com/113001/206299850-a0d81b36-0ac2-476f-bbbd-74c02fcb64e2.png"></a>

I have no idea what would cause this or how to fix it. I've installed this several other times in the past on other repos without issues.

**Comment by martinthomson** [comment]
Ah, you caught a typo.  My apologies.  I'll fix it promptly, but you will need to add a "T" to "GITHUB_OUPUT" in your repository.

**Comment by martinthomson** [comment]
Fixed in 41bb904

**Comment by aaronpk** [comment]
oh, thank you, I didn't even notice that!
