### ISSUE TITLE
setup.py location

### ISSUE THREAD

**Issue by nedmsmith** [martinthomson/i-d-template#359]
I'm getting build errors on a Mac where % make produces the following error
----
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
----

Where is the setup.py file supposed to come from? 

% make -f venv.mk debug-venv
doesn't have a setup.py file - I assume it should?
SETUP_PY="                  "

**Comment by martinthomson** [comment]
This is likely the same issue as #358.  I assume that you are on python 3.11, yes?

**Comment by nedmsmith** [comment]
I upgraded with homebrew which brought me to 3.9. I may try uninstalling and reinstalling.
Should I expect setup.py is generated or is it part of python install?

From: Martin Thomson ***@***.***>
Reply-To: martinthomson/i-d-template ***@***.***>
Date: Saturday, January 7, 2023 at 3:20 AM
To: martinthomson/i-d-template ***@***.***>
Cc: "Smith, Ned" ***@***.***>, Author ***@***.***>
Subject: Re: [martinthomson/i-d-template] setup.py location (Issue #359)


This is likely the same issue as #358<https://github.com/martinthomson/i-d-template/issues/358>. I assume that you are on python 3.11, yes?

**Comment by nedmsmith** [comment]
Yes, this is the same issue as #358

**Comment by martinthomson** [comment]
Thanks.  I'll close this and we can track it over there.
