### ISSUE TITLE
Custom CSS misrenders olPercent dt elements

### ISSUE THREAD

**Issue by davidben** [martinthomson/i-d-template#367]
The `<ol>` tag in xml2rfc allows writing things like `<ol type="(%c)">`. xml2rfc renders them as HTML `<dl>` lists with tag `olPercent`:
https://github.com/ietf-tools/xml2rfc/blob/main/xml2rfc/writers/html.py#L1923

This renders fine in xml2rfc's built-in style, but in the custom CSS style used by this repo, `dl > dt` gets a `min-width` and `margin-right` that causes a large indent.
https://github.com/martinthomson/i-d-template/blob/main/v3.css#L338-L342

**Comment by martinthomson** [comment]
Thanks for raising this.  I don't know what the right indent is, but what was there was clearly bad.

**Comment by larseggert** [comment]
Is this something the datatracker should adopt?

**Comment by martinthomson** [comment]
Oh, yeah.  I should probably test that out as well.  I'll flag you on the change @larseggert.
