### ISSUE TITLE
Error pushing to gh-pages

### ISSUE THREAD

**Issue by peterthomassen** [martinthomson/i-d-template#369]
[This build](https://github.com/johanix/draft-johani-tld-zone-pipeline/actions/runs/4244593003/jobs/7379034309) fails with:
```sh
git -C /tmp/ghpages80 push -qf https://****@github.com/johanix/draft-johani-tld-zone-pipeline gh-pages
make[1]: *** [lib/ghpages.mk:127: ghpages] Error 1
make: *** [lib/ghpages.mk:121: ghpages] Error 2
```

It's unclear why that failure occurs (it appears to be hidden behind the `-q` flag). Do you have any insights?

Thank you for this great tool.

@johanix

**Comment by martinthomson** [comment]
The only hint I can provide is to check in the repository [settings](https://github.com/johanix/draft-johani-tld-zone-pipeline/settings/actions).  It is possible that your workflow permissions are set to read-only.

![image](https://user-images.githubusercontent.com/67641/220784192-4f4d752c-b503-4728-9450-41e011974ee1.png)

(The `-q` flag is unfortunately necessary.  `git` tends to broadcast the token we provide if it is allowed to speak.)

**Comment by martinthomson** [comment]
I've updated the instructions on the template repository to provide a link to this setting.  I can't change it for you, but it should be easy enough to follow from there.

**Comment by peterthomassen** [comment]
Thank you!
