### ISSUE TITLE
Variables are not set when CI is true

### ISSUE THREAD

**Issue by fno2010** [martinthomson/i-d-template#376]
[This conditional branching](https://github.com/martinthomson/i-d-template/commit/ae2c1fbe5ea3cbcf97694bcaa1595dd66665b639#diff-ca72bef3a929f0892f9ebd161ab0a846a03bd0432d3cdd126d03dca4b7573275R132) will never be executed. Because when `$(CI)` is `true`, `$(REQUIREMENTS_TXT)` will be empty.

As a result, the `$(python)` and `$(xml2rfc)` variable will not be set:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/actions/runs/4606191226/jobs/8139185691#step:6:13

```
cat draft-ietf-alto-oam-yang.md  | kramdown-rfc --v3 | lib/trace.sh draft-ietf-alto-oam-yang.xml -s venue  lib/add-note.py | lib/trace.sh draft-ietf-alto-oam-yang.xml -s v2v3  --v2v3 /dev/stdin -o /dev/stdout >draft-ietf-alto-oam-yang.xml
lib/trace.sh: line 28: --v2v3: command not found
```

**Comment by martinthomson** [comment]
Sorry about that.  I've fixed it in fda1ebc
