### ISSUE TITLE
On Ubuntu 22.04 the virtualenv doesn't have bin/pip available

### ISSUE THREAD

**Issue by BrianSipos** [martinthomson/i-d-template#382]
When I follow the installation instructions and run `make -f lib/setup.mk` the setup gets part way through and then fails out with the message:
```
$REPO/lib/.venv/bin/pip install  -r lib/requirements.txt
bash: line 1: $REPO/lib/.venv/bin/pip: No such file or directory
```

I made a local change to replace `.venv/bin/pip` with `.venv/bin/python -m pip`, cleared out the old `.venv` tree, and then the setup seemed to go through correctly.

**Comment by martinthomson** [comment]
Strange.  Do you have the [python3-pip](https://packages.ubuntu.com/jammy/python3-pip) package on the system?  A venv should include pip if pip is on the system.

**Comment by martinthomson** [comment]
pip is invoked either from the venv or using `python -m pip` now, so this should be OK.
