### ISSUE TITLE
main.mk basic targets omits xml

### ISSUE THREAD

**Issue by nedmsmith** [martinthomson/i-d-template#384]
Why isn't xml one of the basic targets? 

xml is one of the expected formats for datatracker I-D upload
A manual conversion is required to move from one of the basic target formats to xml

Just curious.

**Comment by martinthomson** [comment]
`make next` will generate xml, but I would prefer to encourage the use of tagging or - in extremis - `make upload`.

**Comment by martinthomson** [comment]
I should have added that it doesn’t make sense to build a -latest version of the XML. That is what would be the equivalent of what the `html` or `txt` targets create. You can’t submit that file.
