### ISSUE TITLE
aasvg install

### ISSUE THREAD

**Issue by nedmsmith** [martinthomson/i-d-template#385]
aasvg doesn't appear to be installed by default
e.g.: $ npm install -g aasvg

Should it be?

**Comment by martinthomson** [comment]
aasvg is installed in CI images, but I am considering removing that. The way that I encourage people to access aasvg is to install it locally (`npm i —save aasvg`) and then check in `package.json` (`git add package.json;git commit`. Then, as long as people have `npm` installed, running `make` will install it.

**Comment by ounsworth** [comment]
I'll admit that I got stuck on this for longer than I want to admit. Why not have your `make` install npm (I didn't have it, that was my problem).

**Comment by martinthomson** [comment]
Firstly, the variety of methods that might be used to obtain NPM are diverse enough that I didn't want to do that work.  Secondly, I want to ensure that this doesn't alter the environment in which it runs.  There is a warning that shows if you don't have `npm`, but I guess that there is a lot of output to work through, so it can get lost.
