### ISSUE TITLE
Odd behavior in recently moved GitHub repo - I'm trying to update the venue

### ISSUE THREAD

**Issue by SpencerDawkins** [martinthomson/i-d-template#386]
For background - the MOQ working group has adopted the draft formerly known as https://github.com/moq-wg/moq-requirements. The chairs, @afrind and @hardie, have moved this into the IETF GitHub organization as https://github.com/moq-wg/moq-requirements.

All seemed well in the new repo (I was able to submit https://github.com/moq-wg/moq-requirements/pull/105, and @fiestajetsam was able to review it), but then, I noticed that the venue information in the draft was still pointing to the old repo:

> Note to Readers
> RFC Editor: please remove this section before publication
> 
> Source code and issues for this draft can be found at https://github.com/fiestajetsam/draft-gruessing-moq-requirements.
> 
> Discussion of this draft should take place on the IETF Media Over QUIC (MoQ) mailing list, at https://www.ietf.org/mailman/listinfo/moq.

So, I'm trying to correct that venue information, and failing badly. 

More details in next comment.

**Comment by martinthomson** [comment]
Hi Spencer, the process for updating files is different than the process for updating the venue information.

Let's assume that you have a clean checkout.  From there you can do `make update-venue`.  This is a separate target from `update-files` because it is the only one that changes the draft itself.

I don't know why updating files isn't working for you.  It worked for me on a clean checkout.  I can push that to a branch for you if you like.  (The modified files are indeed what `make update-files` will touch, though this includes the draft itself, which is not touched by that process.)

**Comment by SpencerDawkins** [comment]
Hi, Martin, 

I'm sorry, but I'm thick. I now hear what you are saying, when you say 

> Let's assume that you have a clean checkout. From there you can do make update-venue. This is a separate target from update-files because it is the only one that **changes the draft itself**.

The .md file does, in fact, have a Note_to_Readers that points to the right place (now).

> --- note_Note_to_Readers
> 
> *RFC Editor: please remove this section before publication*
> 
> Source code and issues for this draft can be found at
> <https://github.com/fiestajetsam/draft-gruessing-moq-requirements>.
> 
> Discussion of this draft should take place on the IETF Media Over QUIC (MoQ)
> mailing list, at <https://www.ietf.org/mailman/listinfo/moq>.

So I think you're also telling me that the .note.xml file that (IIRC) was used to insert this note into the generated draft versions is no longer required, and that I can safely delete that. Does that sound correct to you?

**Comment by martinthomson** [comment]
I didn't say it explicitly, but `.note.xml` is not necessary if you are using kramdown for authoring.  It is still used if you use a different authoring format, but then I can't think of many good reasons to do THAT. :)

**Comment by SpencerDawkins** [comment]
Hi, @martinthomson, thank you for clarifying that! As you said, I was using kramdown, and I can't think of a good reason to do anything else in my own case. 

I was confused because the .note.xml file wasn't being updated, but didn't check to see if my .md file had the correct information. It does, and now @fiestajetsam and I know what to do .

Deleting extraneous .note.xml file in 3, 2, 1 ...
