### ISSUE TITLE
xml2rfc.tools.ietf.org -> bib.ietf.org

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#387]
https://github.com/martinthomson/i-d-template/blob/3eaf04d967d3812d9a61675b89ee1b04314ad83d/config.mk#L46

seems to need to now be

```
XML_RESOURCE_ORG_PREFIX ?= https://bib.ietf.org/public/rfc
```

**Comment by henkbirkholz** [comment]
So...  this led to various delays today :sweat_smile: Good to see that there is already a filed issue.
