### ISSUE TITLE
Not getting ghpages updated on Travis

### ISSUE THREAD

**Issue by jimsch** [martinthomson/i-d-template#39]
The problem is that Travis_Pull_Request is set to false.  You can see the environment dump at
https://travis-ci.org/sacmwg/vulnerability-scenario/builds/121561135#L617

**Comment by jcjones** [comment]
This may have broken when PR #36 landed.
I'm not sure how to use the inline `if` construction to get this to work the way we want, so I replaced the the `CI_IS_PR` logic [in my bikeshed fork](https://github.com/jcjones/bikeshed-template/commit/d6a69e4ae6d2b978a68a15a165705b81a052b344):
```
ifeq (true, $(CI_PULL_REQUESTS))
# If CI_PULL_REQUESTS is true, always treat as a PR.
CI_IS_PR = true
else
ifeq (false, $(TRAVIS_PULL_REQUEST))
# If $TRAVIS_PULL_REQUEST is the word 'false', it's a branch build.
CI_IS_PR = false
else
# Otherwise, this is a PR and $TRAVIS_PULL_REQUEST is the PR number
CI_IS_PR = true
endif
endif
```

**Comment by martinthomson** [comment]
Thanks @jcjones, sadly that doesn't work for Circle CI, which will always end up with CI_IS_PR being true, since CI_PULL_REQUESTS is a list of PRs.  I currently have an even more complicated set of checks, none of which are easily conducive to inline hacks:

```
ifdef CI_PULL_REQUESTS
CI_IS_PR = true
else
# Circle makes this easy
ifdef TRAVIS_PULL_REQUEST
ifeq (false,$(TRAVIS_PULL_REQUEST))
# If $TRAVIS_PULL_REQUEST is the word 'false', it's a branch build.
CI_IS_PR = false
else
CI_IS_PR = true
endif
else
CI_IS_PR = false
endif
endif
```
