### ISSUE TITLE
Publish new draft run failed

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#393]
I might have had a race condition where I did "make publish" but just in case:
```
Run date -u "+date=%FT%T" >>"$GITHUB_OUPUT"
  date -u "+date=%FT%T" >>"$GITHUB_OUPUT"
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/7c2d6d46-646f-4e6a-a2e6-811590e6cf4a.sh: line 1: : No such file or directory
Error: Process completed with exit code 1.
```

**Comment by martinthomson** [comment]
¯\\\_(ツ)\_/¯

Actions sometimes fail, but that's a new one.  I can't see how a race condition would produce that outcome.  More likely there was a failure in the hardware.  Apparently GitHub Actions write to a UUID-named file before running it.  And sometimes the write fails.

**Comment by martinthomson** [comment]
Chalking this up as a transient problem.
