### ISSUE TITLE
Noise in "Compare Editor's Copy to Working Group Draft"

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#394]
The TXT files generated by datatracker have page numbers, the TXT file generated here doesn't.
This leads to the TOC being completely different, which turns up as noise in the rfcdiff.

<img width="993" alt="image" src="https://github.com/martinthomson/i-d-template/assets/23118/62f92d0a-c78a-4711-af03-0da6fd5cfda9">

**Comment by martinthomson** [comment]
Yes.  The datatracker should stop producing paginated versions of drafts.

**Comment by martinthomson** [comment]
Clearly our views differ.  I am happy to add an affordance for you if you believe that pagination is necessary (some affordances already exist, but they are not documented and they probably aren't narrowly-enough targeted).

https://author-tools.ietf.org/iddiff?url1=draft-irtf-cfrg-hpke-11&url2=rfc9180&difftype=--html is at least one reason I think speaks in favour of my position, should you be inclined to listen to arguments on this point (I understand that this is a point of religion in parts of the community; I don't want to imply that of you, of course).

**Comment by cabo** [comment]
I do believe that pagination improves working with drafts.
But my request here was specifically motivated by the rfcdiff noise generated by the different settings; it generally helps to have TXT generation settings that are the same between different ways of generating them.

The HPKE example is formidable.  It clearly shows that rfcdiffs are less useful over long stretches of text development.
But it also underscores the above point: Here the big TXT generation change was the change in treatment of <tt by xml2rfc 3.10.0 ("train wreck" threads of discussion).  For a more useful diff, the input should have been regenerated from source with that new version of TXT generation.

**Comment by martinthomson** [comment]
Try setting `TEXT_PAGINATION := true` to turn on pagination.

(I didn't want to use this as cause to distract you with the whole \<tt mess, though I think that "should have been regenerated" is a surprising position to hear.  I do agree that diffs based on XML source would be an improvement over status quo, but I tend to think that it is unnecessary.  Text output in unpaginated form doesn't need any special processing to produce a useful diff, even if there is sometimes a little noise.  That is more or less the best use of text output.  That iddiff is necessary is a bug, not something to double down on.)

**Comment by cabo** [comment]
Thank you!

(Now I just need an update to kramdown-rfc [and another one to utftex?] to trickle through:

https://author-tools.ietf.org/api/iddiff?doc_1=draft-ietf-cbor-time-tag&url_2=https://cbor-wg.github.io/time-tag/draft-ietf-cbor-time-tag.txt

)
