### ISSUE TITLE
The "versioned" directory should be ignored?

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#395]
I guess that goes in the instructions, or maybe configured during setup?  "echo versioned/*xml >>.gitignore" ?

**Comment by martinthomson** [comment]
This is already listed in https://github.com/martinthomson/i-d-template/blob/10f9400b9cc2b61cb5f2b8a39a8831e431036220/template/.gitignore#L16
But it might be that you started from an old copy of the repository that predates that addition.  `make update-files` will correct the omission if you like the automated approach.
