### ISSUE TITLE
Apparently need utftex 1.24 (have 1.22) in docker image

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#396]
1.22 says:
ERROR: Too few mandatory arguments to command (1x)
when I give it
{acc \over \mathrm{s}}

1.24 works (on my machine™)

**Comment by martinthomson** [comment]
We're almost due for the automated build of the images, but I poked it and so it should be updated shortly.

**Comment by cabo** [comment]
This one is long overtaken by events, but it would be nice to get the newest version of kramdown-rfc into the docker image.
