### ISSUE TITLE
draft submission with CI fails

### ISSUE THREAD

**Issue by prmanna** [martinthomson/i-d-template#405]
Hi Martin,

We are trying to publish a new draft for this.
https://github.com/italobusi/draft-poidt-teas-actn-poi-assurance

Based on the suggestion in [SUBMITTING.md](https://github.com/martinthomson/i-d-template/blob/main/doc/SUBMITTING.md), we have used **Continuous Integration** step..

This is erroring out. 
https://github.com/italobusi/draft-poidt-teas-actn-poi-assurance/actions/runs/6182684349/job/16782903641

Can you please help, what is missing in our steps?

Thanks.

**Comment by martinthomson** [comment]
The action output says: "Maybe you meant to name the label 'draft-poidt-teas-actn-poi-assurance-01' instead."  Maybe you can try that.

**Comment by prmanna** [comment]
I have tried with the following commands, but got exactly the same error:
 
git tag -a 'draft-poidt-teas-actn-poi-assurance-01'
git push origin 'draft-poidt-teas-actn-poi-assurance-01'
 
I have tried the semi-automated process and got a similar error (I have lost the error file)
 
I have also tried the manual process with the following command:
 
make draft-poidt-teas-actn-poi-assurance-01.xml 2> manual.txt
 
Also the manual process has failed with the error log attached
 
IMHO, the key issue is the following error message (in common to all the attempts):
 
make: *** No rule to make target 'draft-poidt-teas-actn-poi-assurance-01.xml'.

**Comment by martinthomson** [comment]
Thanks for pointing out an error in the documentation.  Try:

```
$ make versioned/draft-poidt-teas-actn-poi-assurance-01.xml
```

**Comment by prmanna** [comment]
prmanna$ make versioned/draft-poidt-teas-actn-poi-assurance-01.xml
make: *** No rule to make target `versioned/draft-poidt-teas-actn-poi-assurance-01.xml'.  Stop.

**Comment by martinthomson** [comment]
Hmm, try `make extra` and then try that target again.  It is possible that you have an older version of `make` installed.

**Comment by prmanna** [comment]
prmanna$ make extra
VERSIONED="versioned" lib/build-targets.sh draft-poidt-teas-actn-poi-assurance  >>.targets.mk

still the same issue exists.

**Comment by italobusi** [comment]
We have been able to generate the .txt file but there is still some error when generating the .xml file

This is the command:

`make next > output.txt 2> error.txt`

This is the output file: [output.txt](https://github.com/martinthomson/i-d-template/files/12683278/output.txt)

This is the error file: [error.txt](https://github.com/martinthomson/i-d-template/files/12683280/error.txt)

**Comment by martinthomson** [comment]
Thanks for sharing those error messages.  One potential problem is that the versioned draft seems to be generated from the text file, not the XML.  Have you checked in the text file?

Also, the error messages are informative.  You might need to convert line endings.  Something is taking a file with '\r\n' line endings (windows) but processing it as though it were unix line endings ('\n' only), so the '\r' is being appended to variable names.

**Comment by italobusi** [comment]
> Thanks for sharing those error messages. One potential problem is that the versioned draft seems to be generated from the text file, not the XML. ~Have you checked in the text file?~ I see that you have checked in the text output. You should not.

I have fixed the EOL issue but I am still running into the same issue

How can I avoid checking in the text output?

I have just run this command:

`make next > output.txt 2> error.txt`

This is the new output file: [output.txt](https://github.com/martinthomson/i-d-template/files/12685185/output.txt)

This is the new error file: [error.txt](https://github.com/martinthomson/i-d-template/files/12685190/error.txt)

**Comment by italobusi** [comment]
BTW, this is what I can get with `make -v`

```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by martinthomson** [comment]
Try `git rm -f *.txt *.html` to remove the text file.

**Comment by italobusi** [comment]
> This is the new output file: [output.txt](https://github.com/martinthomson/i-d-template/files/12685185/output.txt)
> 
> This is the new error file: [error.txt](https://github.com/martinthomson/i-d-template/files/12685190/error.txt)

Same issue

This is the new output file: [output.txt](https://github.com/martinthomson/i-d-template/files/12696993/output.txt)

This is the new error file: [error.txt](https://github.com/martinthomson/i-d-template/files/12696991/error.txt)

The recurring error message in all these attempts is:

```
make[1]: *** No rule to make target 'versioned/draft-poidt-teas-actn-poi-assurance-02.xml'.  Stop.
make: *** [lib/targets.mk:28: versioned/draft-poidt-teas-actn-poi-assurance-02.xml] Error 2

```

It is not clear which rule the tool is looking for

**Comment by martinthomson** [comment]
OK, I think that I have a handle on this.

For some reason you don't have any tags.  In order to generate draft-poidt-teas-actn-poi-assurance-02 you need to have one of two tags: draft-poidt-teas-actn-poi-assurance-02 or draft-poidt-teas-actn-poi-assurance-01.  Otherwise, `make extra` won't know how to make rules for those files.  The difference here is that if you tag draft-poidt-teas-actn-poi-assurance-02 explicitly, then the file will be generated from the version that is tagged.  If you only have draft-poidt-teas-actn-poi-assurance-01 tagged, then the -02 files will be created from the current state of the directory, whatever that is (as though your current files are the next version that you want to publish).

**Comment by martinthomson** [comment]
Also, you need to ensure that the .txt and .html files are properly gone.  Make sure to commit after you run `git rm -f`.  Then run `make clean; make extra; make next`.

**Comment by martinthomson** [comment]
I've made some adjustments that should handle the checked in txt/html files better, and also produce a warning if you do that.  That along with the tagging advice might help.

**Comment by italobusi** [comment]
The issue is now fixed

Thanks a lot Martin for your help
