### ISSUE TITLE
Updating Dependencies?

### ISSUE THREAD

**Issue by CxRes** [martinthomson/i-d-template#407]
I am observing that i-d-template (copied over about a month ago) is using older version of dependencies (kramdown-rfc) while building gh-pages branch using GitHub actions. Can this be forced to latest version? Do I have to wait for it to be updated and if so, how long?

**Comment by martinthomson** [comment]
`make update-deps` should run occasionally when you run `make`, but you can run it directly.

**Comment by CxRes** [comment]
Thats what I do on my local install. I meant this question specifically for the build that is being automatically being created on Github via Actions. I would really like for Actions to pick up the latest deps!

**Comment by martinthomson** [comment]
Ah, I see.  There is a periodic build that runs (see https://github.com/martinthomson/i-d-template/blob/main/.github/workflows/docker.yml) and catches the latest updates.  If there is something in particular you want refreshed, let me know and I can poke the build so that it runs earlier.

**Comment by CxRes** [comment]
Yes, please! @cabo made me an experimental feature in kramdown-rfc (thus bumping versions) that I would like to see working when I put up my draft.

**Comment by martinthomson** [comment]
Carsten is good like that :)  I've poked the build, which should take <30 min.

Closing this issue now.  If you need another bump, let me know.

**Comment by CxRes** [comment]
Thanks for the poke! I can confirm I have the latest kramdown-rfc.

I am rather new to the IETF stuff (never in my life I thought I would be writing an RFC), in that little time here Carsten has been absolutely great!
