### ISSUE TITLE
Saved issues link that 404s is created in index page without issues

### ISSUE THREAD

**Issue by CxRes** [martinthomson/i-d-template#408]
A saved issues link is created when creating the index page `index.html`, irrespective of whether any issues exist in the repo. Since there are no issues in the repo, an issues.html is not created. See <https://github.com/CxRes/id-test> and <https://cxres.github.io/id-test/> for a reproduction.

In my own testing however, issues.html got subsequently created, though I am not sure if the push triggered that or whether that was a result of me poking on Github Actions. You can see a blank `issues.html` in this test <https://github.com/CxRes/id-pre-test-2> eventually gets created.

**Comment by martinthomson** [comment]
Yes, this is an asynchronous process, because archiving issues is more expensive.  The link from the README in the repository also ends up with a 404 for a short while too.  The 404 shouldn't last too long.

**Comment by CxRes** [comment]
Hmmm. So what triggers the archiving and `issues.html` being built? Is it just something that happens at a random time later or is it influenced by pushes? or something else?

**Comment by martinthomson** [comment]
It is periodic.  See https://github.com/martinthomson/i-d-template/blob/eb41d49559216fe5b4c4a3c2b6bf214bfe032f15/template/.github/workflows/archive.yml#L4-L5

**Comment by CxRes** [comment]
I am closing the issue. But it would be nice if this behaviour was documented (unless I have missed it)!
