### ISSUE TITLE
Support for Replaces tag

### ISSUE THREAD

**Issue by DavidSchinazi** [martinthomson/i-d-template#409]
The automated pipeline that converts releases/tags into automatic draft uploads is amazing. The only place where it fails is when a document gets adopted. In that scenario I submit `draft-ietf-foo-bar-00.xml` manually to set the Replaces tag.

Now that https://github.com/ietf-tools/datatracker/pull/4037 has landed and https://github.com/ietf-tools/datatracker/issues/3286 has been resolved, the datatracker API allows setting this tag in JSON. So we could automate that here. I'm imagining a simple regex that would detect a newly adopted draft `draft-ietf-foo-bar-00` and would look for a `draft-author-foo-bar-nn` tag to replace it.

I'm happy to write a PR for this feature, just wanted to make sure this wasn't in progress before starting. Also happy to take tips/pointers/thoughts on it.

**Comment by martinthomson** [comment]
Have you tried using the automated process for the `draft-ietf-foo-bar-00` submission?  I believe that it should work.  Maybe I need to update documentation...

**Comment by DavidSchinazi** [comment]
Oh I never tried. Is it set up to twiddle the Replaces tag?

**Comment by martinthomson** [comment]
[Documentation](https://github.com/martinthomson/i-d-template/blob/main/doc/SUBMITTING.md#submitting-drafts) says:

> If you have renamed a draft, this will also set the "replaces" field for you automatically, based on the git history of the file.

This is a little bit magic (git doesn't track file renames, it can only sort of guess...)

**Comment by DavidSchinazi** [comment]
Oh sweet that's awesome, thanks for doing that. I'll give it a try next time something gets adopted.
