### ISSUE TITLE
Warn about unpreferred source code types

### ISSUE THREAD

**Issue by ioggstream** [martinthomson/i-d-template#423]
## I expect

- to get warnings when using a sourcecode type not listed in https://www.rfc-editor.org/materials/sourcecode-types.txt

## Notes

- where is the best place to put this check?

**Comment by martinthomson** [comment]
> where is the best place to put this check?

one of two places, neither of them here :)

* kramdown-rfc if you are using that tool.
* xml2rfc

The reason you would only want to warn is that the list of allowed types might need to change faster than whatever tool can. Both tools are well maintained, but things can move quickly.
