### ISSUE TITLE
lib/setup.mk can't find my docname, but I think it's there. 

### ISSUE THREAD

**Issue by SpencerDawkins** [martinthomson/i-d-template#425]
When I committed to the master branch in [my repo](https://github.com/SpencerDawkins/rfc3113bis), the GitHub action ([here](https://github.com/SpencerDawkins/rfc3113bis/actions/runs/7690742431/job/20954988608)) returned 

> warning: lib/default-branch.py: correcting the default branch locally:
> warning: lib/default-branch.py:     git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
> lib/setup.mk:20: *** Check names: draft-dawkins-iab-rfc3113bis.md should include a name of draft-dawkins-iab-rfc3113bis-latest.  Stop.

When I search for "draft-dawkins-iab-rfc3113bis-latest" in https://raw.githubusercontent.com/SpencerDawkins/rfc3113bis/main/draft-dawkins-iab-rfc3113bis.md, Chrome finds that string, specifically as 

> docname: draft-dawkins-iab-rfc3113bis-latest

When I run make on my local copy, that returns 

> make: *** No targets specified and no makefile found.  Stop.

which looks like it might be caused by the same problem. 

I'm sure I'm missing something, but if you happen to notice what I'm missing, that would be SUPER helpful!

And thank you, as always, for this template.

**Comment by martinthomson** [comment]
I can't work it out.  https://github.com/SpencerDawkins/rfc3113bis/pull/1 was the result of me running setup locally (which takes a little bit more than just running `make`, but not much: `git clone https://github.com/martinthomson/i-d-template lib; make -f lib/setup.mk`).

**Comment by SpencerDawkins** [comment]
Thank you, @martinthomson -  I'm closing this issue, and the repo is up and working now.
