### ISSUE TITLE
When moving a single-doc repo to a multi-repo project

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#430]
There seem to be some extra steps that need to be done. For example, tweaking the gh-pages output to put things in subdirectories. Docs or notes on those steps would be incredibly helpful.
See https://github.com/tlswg/tls12-frozen for my example.  tnx.

**Comment by martinthomson** [comment]
There isn't really anything special involved.  What you have in that repo appears to be working perfectly well.

The only thing you might do is provide links to the editor's copy.  `make update-readme` will do that for you.  I added a note to the [features summary](https://github.com/martinthomson/i-d-template/blob/main/doc/FEATURES.md) that covers this.

**Comment by richsalz** [comment]
awesome, thanks!
