### ISSUE TITLE
make idnits doesn't work after draft rename

### ISSUE THREAD

**Issue by alvestrand** [martinthomson/i-d-template#446]
Repository: https://github.com/alvestrand/id-abs-capture-timestamp/tree/main

I created the draft draft-alvestrand-avtcore-abs-capture-timestamp.md - everyting seemed to work.
I then ran
```make idnits```
and got an error message that the draft name was too long.

I renamed the .md file to draft-alvestrand-avtcore-abs-capture-time.md and made the corresponding change in the "docname" attribute.

However, when I then ran ```make idnits```, I got the error message
<blockquote>
make: *** No rule to make target 'versioned/draft-alvestrand-avtcore-abs-capture-time-00.xml', needed by 'versioned/draft-alvestrand-avtcore-abs-capture-time-00.txt'.  Stop.
</blockquote>

This seems strange.

**Comment by martinthomson** [comment]
Yeah, that's a surprising one.  Generally, you will find that things like renames are best followed by `make clean`.  I can't make the tool perfectly robust against all potential failures.  (The file you want to nuke is `.targets.mk`).

**Comment by alvestrand** [comment]
Thanks, that worked. Submitted a PR to add that to the documentation page I was reading.
