### ISSUE TITLE
[RESOLVED] make[1]: *** [lib/ghpages.mk:141: ghpages] Error 1

### ISSUE THREAD

**Issue by peppelinux** [martinthomson/i-d-template#448]
After months of succesful deployments, gh-pages deployments stop working without any evident reason

it worked fine until the 1 July of this year, as made evident by commit history: https://github.com/peppelinux/draft-demarco-oauth-status-assertions/commits/main/

here the related log: https://github.com/peppelinux/draft-demarco-oauth-status-assertions/actions/runs/11178706405/job/31076823790

I have tested that this issue is not linked with the contents of the draft, I created another branch and did an hard reset to the last commit working fine with the workflow.

Unfortunately the error about `lib/ghpages.mk:141` does not give any information about the cause of the problem and how to resolve it, therefore I am here to get some further information about what's the cause of this issue and how to resolve it.

**Comment by martinthomson** [comment]
This is quite likely down to a feature that we implemented for QUIC interacting with GitHub permissions.  We trim the history of the `gh-pages` branch so that the size of the repository doesn't blow out.  You can run that process manually (`make gh-pages` from a command line), or disable it by setting `GHPAGES_COMMIT_TTL` to something very large.

**Comment by peppelinux** [comment]
@martinthomson thank you, I confirm that the issue was resolved thanks to your support

https://github.com/peppelinux/draft-demarco-oauth-status-assertions/actions/runs/11562880280/job/32185539821

I suggest to publish/share this knowledge to hint ppl what to not do to get things working

**Comment by martinthomson** [comment]
I think that I might just disable the feature in CI.  The cleanup here is a bit of dual edge thing: it saves some space, but it also loses history for the branch.
