### ISSUE TITLE
wrong FETCH_HEAD when using i-d-template as named submodule

### ISSUE THREAD

**Issue by obgm** [martinthomson/i-d-template#45]
After having passed the `--name i-d-template` parameter to `git submodule add`, the `FETCH_HEAD` in L7 of `lib/update.mk` is not recognized any more (because now it's `.git/modules/i-d-template/FETCH_HEAD` instead of `.git/modules/$(LIBDIR)/FETCH_HEAD). 

```
$ cat .gitmodules 
[submodule "i-d-template"]
	path = lib
	url = https://github.com/martinthomson/i-d-template
$ ls .git/modules/
i-d-template
```

Unfortunately, I am not sure how to fix this properly (maybe by saying "Don't use `--name`" in the README).

**Comment by martinthomson** [comment]
So I wrote that code to fail soft, which means that FETCH_HEAD being empty wouldn't hurt.  Are you seeing the code update too often?

**Comment by obgm** [comment]
It tries to update every time when I call make because `$(FETCH_HEAD)` in line 11 of update.mk is empty, so `UPDATE_NEEDED` is set to `true`.
Indeed, that does not do any real harm -- the conversion process still works fine. It was just confusing until I have understood what's going on.

**Comment by martinthomson** [comment]
Yeah, I think that's distracting.  I've updated to suppress updates for you.  You should update.  (I could parse .gitmodules, but that's too much.  Not many people using submodules.)

See e0a9468

**Comment by obgm** [comment]
Thanks!
