### ISSUE TITLE
Make generates an error on MacOS

### ISSUE THREAD

**Issue by yaronf** [martinthomson/i-d-template#459]
```
sed: 2: "s/^{::include\(-nested\ ...": undefined label ';d'
```

This apparently comes from this line: https://github.com/martinthomson/i-d-template/blob/a415151424d9edf13c49fe204515da8621ed1ae9/main.mk#L47

**Comment by martinthomson** [comment]
Let me know if my fix doesn't work for you.  (`make update` should get it to you.)

**Comment by yaronf** [comment]
The `sed` line seems to be fixed now, thanks, but now I'm getting:

> make: *** No rule to make target '', needed by 'draft-ietf-wimse-s2s-protocol.xml'.  Stop.

Which means the actual document does not build.

**Comment by martinthomson** [comment]
Ah, the fix was incomplete.  On the plus side, you will now have the draft build properly if you update one of the included files.
