### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by fpalombini** [martinthomson/i-d-template#52]
Hello,

First of all thank you so much for this work!
About the issue, I just wanted to say that I set up a repository in September, and that at the time I didn't have any problems. Now I tried again, and this time I'm running on some issues. When I run: "make -f lib/setup.mk":

`  $ make -f lib/setup.mk`
`lib/main.mk:91: .targets: No such file or directory`
`lib/setup.mk:44: lib/.template-files.mk: No such file or directory`
`lib/setup.mk:30: *** You have uncommitted changes, please commit them before running setup.  Stop.
`

And of course at this point a git status shows that .targets and lib/ are untracked.
I go on and add them to the .gitignore, after which the setup goes on ok.
Next problem is with "make ghpages"

` $ make ghpages`
`lib/main.mk:91: .targets: No such file or directory`
`cp draft-ietf-core-object-security.html index.html`
`mkdir /tmp/ghpages9540`
`cp -f index.html draft-ietf-core-object-security.html draft-ietf-core-object-security.txt /tmp/ghpages9540`
`git clean -qfdX`
`git checkout gh-pages`
`error: The following untracked working tree files would be overwritten by checkout:`
`        index.html`
`Please move or remove them before you can switch branches.`
`Aborting`
`make: *** [ghpages] Error 1`

Removing doesn't really help of course. since index is copied in the beginning.

Am I doing something wrong?

**Comment by martinthomson** [comment]
OK, I think that the setup issue was a regression.  I've a patch inbound for that.  The odd part is that - as you can see - git clean is run before trying to check out the gh-pages branch.  That should have removed index.html.  I have a few ideas, I'll try to test them out today.

**Comment by martinthomson** [comment]
@fpalombini, if you can, test out the branch that I just pushed.  You will have to checkout the `subcogh` branch of the template to use it.  I've cleaned up the way that I manage the ghpages target so that it operates from a clone rather than checking out the current directory.  It should be less disruptive and more reliable as a result.

**Comment by fpalombini** [comment]
Thanks, it works perfectly now!

Only one comment, by setting up a new repository, I had to push the changes on the gh-pages branch, which is now not indicated in the doc. More precisely:

`make -f lib/setup.mk`
`git push`
`make ghpages`
`git checkout gh-pages`
-- "Your branch is ahead of 'origin/gh-pages by 1 commit.'
`git push`

May be good to add that in the doc.

**Comment by martinthomson** [comment]
Yeah, I try to avoid pushing.  The only reason that the setup pushes to gh-pages is that not doing it messes with a bunch of other things.
