### ISSUE TITLE
Feature request:  Put the output of "make diff" into ghpages

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#55]
Would be nice to have, in addition to the official/editor's links, an easy-to-parse diff between them.  You already have "make diff", so it seem like it would "just" be a matter of creating the diff, stuffing it into the ghpages output, and adding the links to the index files you create.

(If you don't get to it, I might see if I can decode your Makefiles at some point over the holiday.)

**Comment by martinthomson** [comment]
Anything you want to add to ghpages can be made a prerequisite of the target.  That's the easy part.

Identifying the old version of each file requires a bit of mucking around.  You can try to decipher the diff stuff, but that's black arts level 4 (and on my list of things to clean up some day).

**Comment by MikeBishop** [comment]
Actually, I just saw that your template README now points to live rfcdiff and just gives the URLs of the ghpages copy.  That's an equally elegant solution to the same problem....  Shall we put that on the QUIC README?

**Comment by martinthomson** [comment]
I'm happy with that.  I don't find myself using it, but I'm the sort that follows more closely than others.  I'm sure that it will come useful if I have to ever build a change log.  Speaking of which...

**Comment by martinthomson** [comment]
The latest generate html and markdown template includes URLs, which should be sufficient.  We can tweak the pages that use this.
