### ISSUE TITLE
gh-pages clone error in Travis

### ISSUE THREAD

**Issue by fpalombini** [martinthomson/i-d-template#66]
The error I get is: "attempt to fetch/clone from a shallow repository" after the `git clone -q  -b gh-pages . /tmp/ghpages****`

By doing a very short google search, it seems to be a Travis problem linked to the number of commits existing, but I was wondering if there was a way to patch this in the ghpages script itself.

[This](https://travis-ci.org/core-wg/oscoap/builds/182597537) is a build failing, while [this one](https://travis-ci.org/core-wg/oscoap/builds/182539978) passed.

(make ghpages manually does work)

**Comment by martinthomson** [comment]
Try updating your `.travis.yml` with the [latest template](https://github.com/martinthomson/i-d-template/blob/master/template/.travis.yml).

**Comment by fpalombini** [comment]
It works, thanks!
