### ISSUE TITLE
gh-pages pollution

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#68]
Check out the gh-pages branch of the QUIC repo.  The old versions of the documents pre-rename are there, as well as leftovers from every defunct branch that ever built gh-pages.  Should there be some pruning to make sure we drop old build artifacts, or does it not matter since those things are going to live forever in git anyway, whether they're in the current state or not?

**Comment by martinthomson** [comment]
That was intentional. It is possible perhaps to do a cleanup occasionally, but I don't know what trigger you might use to do that.

**Comment by MikeBishop** [comment]
Well, if you wanted to keep it clean as you go, you could just delete all *.html, *.txt in the directory before building the new ones, plus delete folders for branches that no longer exist if you're on master.  However, if you want to preserve the artifacts for a while, maybe a "make ghpagesclean" target that would do the same for each branch as a cleanup trigger?
