### ISSUE TITLE
Travis build: fatal: attempt to fetch/clone from a shallow repository

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#70]
[The most recent Travis build for TCP-TLS](https://travis-ci.org/core-wg/coap-tcp-tls/builds/185552264) complains that cloning the gh-pages fetch is not possible, as it is shallow.
Is this something we broke in some way?

**Comment by martinthomson** [comment]
It's probably me.  Try updating your .travis.yml to match the [template](https://github.com/martinthomson/i-d-template/blob/master/template/.travis.yml).

**Comment by cabo** [comment]
Yes, moving up the distribution used for building to "trusty" fixed this.  Thank you!
