### ISSUE TITLE
sed: 1: "/<title[^>]*>/,/<\/titl ...": extra characters at the end of q command

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#77]
On macOS Sierra, make -f lib/setup.mk fails in an interesting way, leaving an empty index.html:

```
DRAFT_NAME=$(echo draft-ietf-lwig-coap.xml | cut -f 1 -d . -); \
	  AUTHOR_LABEL=$(echo draft-ietf-lwig-coap.xml | cut -f 2 -d - -); \
	  WG_NAME=$(echo draft-ietf-lwig-coap.xml | cut -f 3 -d - -); \
	  DRAFT_STATUS=$(test "$AUTHOR_LABEL" = ietf && echo Working Group || echo Individual); \
	  GITHUB_USER=lwig-wg; GITHUB_REPO=coap; \
	  DRAFT_TITLE=$(sed -e '/<title[^>]*>/,/<\/title>/{s/.*<title[^>]*>//;/<\/title>/{s/<\/title>.*//;H;x;q};H;};d' draft-ietf-lwig-coap.xml | xargs echo); \
	  sed -i~ -e 's~{DRAFT_NAME}~'"$DRAFT_NAME"'~g' -e 's~{DRAFT_TITLE}~'"$DRAFT_TITLE"'~g' -e 's~{DRAFT_STATUS}~'"$DRAFT_STATUS"'~g' -e 's~{GITHUB_USER}~'"$GITHUB_USER"'~g' -e 's~{GITHUB_REPO}~'"$GITHUB_REPO"'~g' -e 's~{WG_NAME}~'"$WG_NAME"'~g' README.md CONTRIBUTING.md LICENSE.md
sed: 1: "/<title[^>]*>/,/<\/titl ...": extra characters at the end of q command
```

(No, I don't understand this error message.  But then I'm not an sed expert...)
Hadn't noticed this so far since the travis version seems to work.

**Comment by martinthomson** [comment]
The mac version of sed is so bad.  I have corrected the error, I think.

**Comment by cabo** [comment]
Thanks.  The sed invocation now no longer fails, but I'm still left with an empty index.html.  Need to investigate some more, but this specific issue is now fixed.  Thank you!

**Comment by martinthomson** [comment]
So the setup does leave index.html empty until the first time that the ghpages build is run. What the above probably did was mess with the README in disappointing ways.
