### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by MikeBishop** [martinthomson/i-d-template#78]
One of the great things about Git is that repos are mostly autonomous -- you can commit, switch branches, etc. without network access.

Unfortunately, Kramdown attempts to fetch references *every time*, even if they're already downloaded.  Is there a way we can mute this, so that make (and therefore, commit with the pre-commit hook) can run successfully without being able to refresh the references?

**Comment by cabo** [comment]
You may want to try the KRAMDOWN_OFFLINE support in kramdown-rfc version 1.1

```
KRAMDOWN_OFFLINE= make
```

This will put in surrogates for bib refs it cannot fetch; please don't submit those .txt files then :-)
