### ISSUE TITLE
Travis build failing in ghpages

### ISSUE THREAD

**Issue by fpalombini** [martinthomson/i-d-template#87]
Hi Martin,

Since a couple of days ago the [Travis build](https://travis-ci.org/cbor-wg/cddl) is failing in the make ghpages:

> Error: No gh-pages branch, run `make -f lib/setup.mk setup-ghpages` to initialize it.
> make: *** [fetch-ghpages] Error 1

Do you have any idea why this could be happening? Any help would be appreciated!

**Comment by martinthomson** [comment]
Carsten mentioned the same issue and I had thought that I fixed it.  Based on the implementation, it seems like you have an old version still, but I'll look into it.

**Comment by martinthomson** [comment]
I'm seeing this work with [another repo](https://travis-ci.org/martinthomson/http-encryption/builds/199751584).  Could you retrigger that build?

**Comment by fpalombini** [comment]
Nevermind, the problem was that the repository was set up before that issue was fixed, I thought it was updated but it wasn't. So just updating to the most recent lib worked. I guess I didn't check before since "make gh-pages" manually worked.
Thanks!
