### ISSUE TITLE
"Setup repository" commit: reference tool used

### ISSUE THREAD

**Issue by chrysn** [martinthomson/i-d-template#94]
Please consider adding a note to the "Setup repository" commit like this:

    Setup repository for draft-...
    
    Structure created from the i-d-template repository.

This would help people new to the i-d-template mechanisms discover it in the first place when they set up a draft in the style of other documents in their working group.

**Comment by martinthomson** [comment]
Does that work for you @chrysn?

**Comment by chrysn** [comment]
yes, thank you.
