### ISSUE TITLE
make gh-pages behaving incorrectly

### ISSUE THREAD

**Issue by jimsch** [martinthomson/i-d-template#97]
If you look at the following link https://github.com/core-wg/oscoap/tree/gh-pages you will see that there is a large number of directories that have been created.  These are being created when a merge is being done directly on the project.  

Link to a travis build is https://travis-ci.org/core-wg/oscoap/builds/214279498

**Comment by martinthomson** [comment]
This is a problem with travis.  I'll have to find an old version of git (1.9.1 is ancient) and see if I can work out how to get `git rev-parse --abbrev-ref HEAD` to return the branch.

**Comment by martinthomson** [comment]
Gah, this is awful: https://travis-ci.org/martinthomson/http-encryption#L321

**Comment by martinthomson** [comment]
1254390a455ac949f6637b3282bb23ffbd890785 fixes this.
